const express = require("express")
const { calculateTimeEntries } = require("../services/workforceTime")
const { createTimesheetPdfBuffer } = require("../services/workforceTimesheetRenderer")

const ACTIVITY_TYPES = new Set(["TRAVEL","WORK","STANDBY","BREAK","WORKSHOP","TRAINING","MEETING","ADMIN","WAITING","LEAVE","SICK_LEAVE","UNPAID","OTHER"])
const CREW_ROLES = new Set(["LEAD_TECHNICIAN","ASSISTANT","ADDITIONAL_TECHNICIAN"])
const JOB_RELATED_ACTIVITIES = new Set(["TRAVEL","WORK","STANDBY","WAITING","OTHER"])

function badRequest(message) {
  const error = new Error(message)
  error.statusCode = 400
  return error
}

function canAdminWorkforce(user) {
  return ["ADMIN", "HR"].includes(user?.role)
}

function canApproveTimesheets(user) {
  return ["ADMIN", "MANAGER"].includes(user?.role)
}

function canManageWorkSchedules(user) {
  return ["ADMIN", "MANAGER", "HR"].includes(user?.role)
}

async function assertWorkScheduleEmployeeAccess(pool, user, employeeUserId) {
  if (["ADMIN", "HR"].includes(user?.role)) return
  if (user?.role !== "MANAGER") {
    const error = new Error("Access denied")
    error.statusCode = 403
    throw error
  }
  const assigned = await pool.query(
    "SELECT 1 FROM atec.tblusers WHERE userid=$1 AND manager_user_id=$2 AND COALESCE(is_active,true)=true",
    [employeeUserId, user.user_id]
  )
  if (!assigned.rows[0]) {
    const error = new Error("This employee is not assigned to you")
    error.statusCode = 403
    throw error
  }
}

function isoDate(value = new Date()) {
  return new Date(value).toISOString().slice(0, 10)
}

function safeExcelText(value) {
  const text = String(value ?? "")
  return /^[=+\-@]/.test(text) ? `'${text}` : text
}

function stylePayrollWorksheet(sheet, headerRow, lastColumn, widths) {
  sheet.views = [{ state: "frozen", ySplit: headerRow }]
  sheet.properties.showGridLines = false
  sheet.autoFilter = { from: { row: headerRow, column: 1 }, to: { row: headerRow, column: lastColumn } }
  const header = sheet.getRow(headerRow)
  header.height = 28
  header.font = { bold: true, color: { argb: "FFFFFFFF" } }
  header.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF203F64" } }
  header.alignment = { vertical: "middle", wrapText: true }
  widths.forEach((width, index) => { sheet.getColumn(index + 1).width = width })
}

async function createPayrollWorkbook(ExcelJS, { summaryRows, dailyRows, detailRows, dateFrom, dateTo, generatedBy, statuses }) {
  const workbook = new ExcelJS.Workbook()
  workbook.creator = "ATEC Inspection Platform"
  workbook.company = "FB Crane Builders & Repairs"
  workbook.created = new Date()
  workbook.calcProperties.fullCalcOnLoad = true

  const summary = workbook.addWorksheet("Payroll Summary", { views: [{ showGridLines: false }] })
  summary.mergeCells("A1:K1")
  summary.getCell("A1").value = "ATEC PAYROLL TIME SUMMARY"
  summary.getCell("A1").font = { bold: true, size: 18, color: { argb: "FFFFFFFF" } }
  summary.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF203F64" } }
  summary.getCell("A1").alignment = { vertical: "middle" }
  summary.getRow(1).height = 34
  summary.getCell("A2").value = "Period"
  summary.getCell("B2").value = `${dateFrom} to ${dateTo}`
  summary.getCell("D2").value = "Generated by"
  summary.getCell("E2").value = safeExcelText(generatedBy)
  summary.getCell("G2").value = "Included statuses"
  summary.getCell("H2").value = statuses.join(", ")
  summary.getRow(4).values = ["Employee No.","Employee","Role","Normal Hours","Overtime Hours","Paid Hours","Travel Hours","Standby Hours","Underground Days","Timesheet Days","Job Numbers"]
  summaryRows.forEach((row, index) => {
    const excelRow = 5 + index
    summary.addRow([
      safeExcelText(row.employee_number),safeExcelText(row.employee_name),safeExcelText(row.role),
      Number(row.normal_hours),Number(row.overtime_hours),
      { formula: `D${excelRow}+E${excelRow}`, result: Number(row.normal_hours) + Number(row.overtime_hours) },
      Number(row.travel_hours),Number(row.standby_hours),Number(row.underground_days),Number(row.timesheet_days),
      safeExcelText(row.job_numbers)
    ])
  })
  stylePayrollWorksheet(summary,4,11,[16,28,15,14,15,14,14,15,17,16,24])
  summary.getColumn(4).numFmt = summary.getColumn(5).numFmt = summary.getColumn(6).numFmt =
    summary.getColumn(7).numFmt = summary.getColumn(8).numFmt = "0.00"
  summary.getRow(2).font = { bold: true }

  const daily = workbook.addWorksheet("Daily Totals")
  daily.addRow(["Date","Employee No.","Employee","Role","Status","Normal Hours","Overtime Hours","Paid Hours","Travel Hours","Standby Hours","Underground","Job Numbers","Manager"])
  dailyRows.forEach((row, index) => {
    const excelRow = index + 2
    daily.addRow([
      String(row.timesheet_date).slice(0,10),safeExcelText(row.employee_number),safeExcelText(row.employee_name),
      safeExcelText(row.role),safeExcelText(row.status),Number(row.normal_hours),Number(row.overtime_hours),
      { formula: `F${excelRow}+G${excelRow}`, result: Number(row.normal_hours) + Number(row.overtime_hours) },
      Number(row.travel_hours),Number(row.standby_hours),row.underground_allowance ? "Yes" : "No",
      safeExcelText(row.job_numbers),safeExcelText(row.manager_name)
    ])
  })
  stylePayrollWorksheet(daily,1,13,[13,16,26,15,20,14,15,14,14,15,14,24,24])
  daily.getColumn(1).numFmt = "yyyy-mm-dd"
  ;[6,7,8,9,10].forEach(column => { daily.getColumn(column).numFmt = "0.00" })

  const detail = workbook.addWorksheet("Time Detail")
  detail.addRow(["Date","Employee No.","Employee","Job Number","Job Card","Customer","Activity","Started","Ended","Normal Hours","Overtime Hours","Paid Hours","Underground","Details"])
  detailRows.forEach((row, index) => {
    const excelRow = index + 2
    detail.addRow([
      String(row.timesheet_date).slice(0,10),safeExcelText(row.employee_number),safeExcelText(row.employee_name),
      safeExcelText(row.job_number),safeExcelText(row.worksheet_number),safeExcelText(row.customer_name),
      safeExcelText(row.activity_type),new Date(row.started_at),new Date(row.ended_at),Number(row.normal_hours),
      Number(row.overtime_hours),{ formula: `J${excelRow}+K${excelRow}`, result: Number(row.normal_hours) + Number(row.overtime_hours) },
      row.underground ? "Yes" : "No",safeExcelText(row.brief_details)
    ])
  })
  stylePayrollWorksheet(detail,1,14,[13,16,26,15,17,26,15,19,19,14,15,14,14,34])
  detail.getColumn(1).numFmt = "yyyy-mm-dd"
  detail.getColumn(8).numFmt = detail.getColumn(9).numFmt = "yyyy-mm-dd hh:mm"
  ;[10,11,12].forEach(column => { detail.getColumn(column).numFmt = "0.00" })
  detail.getColumn(14).alignment = { wrapText: true, vertical: "top" }

  const notes = workbook.addWorksheet("Read Me")
  notes.getColumn(1).width = 28
  notes.getColumn(2).width = 92
  notes.addRows([
    ["ATEC Payroll Export","Weekly/monthly timesheet report prepared for payroll review."],
    ["Paid Hours","Normal Hours + Overtime Hours. Travel and standby are shown separately and are not added again."],
    ["Included records",statuses.join(", ")],
    ["VIP Payroll mapping","This workbook is audit-ready. Direct VIP import column mapping must be confirmed against your VIP Payroll import template/specification."],
    ["Period",`${dateFrom} to ${dateTo}`],
    ["Generated by",safeExcelText(generatedBy)]
  ])
  notes.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }
  notes.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF203F64" } }
  notes.getColumn(2).alignment = { wrapText: true, vertical: "top" }
  return workbook
}

async function loadSchedule(client, userId, date) {
  const result = await client.query(`
    SELECT schedule.*
    FROM atec.tblworkschedule schedule
    WHERE schedule.employee_user_id=$1
      AND schedule.effective_from <= $2::date
      AND (schedule.effective_to IS NULL OR schedule.effective_to >= $2::date)
    ORDER BY schedule.effective_from DESC, schedule.scheduleid DESC
    LIMIT 1`, [userId, date])
  const schedule = result.rows[0] || {
    schedule_name: "No assigned schedule",
    travel_treatment: "SPLIT_BY_SCHEDULE",
    rounding_minutes: 1
  }
  const days = schedule.scheduleid
    ? await client.query("SELECT * FROM atec.tblworkscheduleday WHERE scheduleid=$1 ORDER BY weekday", [schedule.scheduleid])
    : { rows: [] }
  schedule.days = Object.fromEntries(days.rows.map(row => [Number(row.weekday), row]))
  return schedule
}

async function loadHolidays(client, startDate, endDate) {
  const result = await client.query(
    "SELECT holiday_date::text FROM atec.tblpublicholiday WHERE active=true AND holiday_date BETWEEN $1::date AND $2::date",
    [startDate, endDate]
  )
  return new Set(result.rows.map(row => String(row.holiday_date).slice(0, 10)))
}

async function calculateDay(client, userId, date) {
  const entries = await client.query(
    "SELECT * FROM atec.tbltimeentry WHERE user_id=$1 AND activity_date=$2::date ORDER BY started_at,timeentryid",
    [userId, date]
  )
  const schedule = await loadSchedule(client, userId, date)
  const holidays = await loadHolidays(client, date, date)
  return {
    schedule,
    calculation: calculateTimeEntries(entries.rows, schedule, holidays)
  }
}

async function rebuildTimesheet(client, userId, date, options = {}) {
  const existing = await client.query(`SELECT * FROM atec.tbldailytimesheet
    WHERE user_id=$1 AND timesheet_date=$2::date`, [userId,date])
  if (!options.force && existing.rows[0] && ["EMPLOYEE_SUBMITTED","MANAGER_APPROVED","HR_ACCEPTED","EXPORTED"].includes(existing.rows[0].status)) {
    const lines = await client.query(`SELECT line.*,
      COALESCE(entry.customer_name_snapshot,line.customer_name) AS customer_name_snapshot,
      COALESCE(entry.job_number_snapshot,line.job_number) AS job_number_snapshot,
      COALESCE(entry.jobcard_reference_snapshot,line.worksheet_number) AS jobcard_reference_snapshot
      FROM atec.tbldailytimesheetline line
      LEFT JOIN atec.tbltimeentry entry ON entry.timeentryid=line.timeentryid
      WHERE line.timesheetid=$1 ORDER BY line.task_number`, [existing.rows[0].timesheetid])
    return {
      timesheet:existing.rows[0],
      lines:lines.rows,
      schedule:existing.rows[0].schedule_snapshot || {},
      normal_hours:Number(existing.rows[0].final_normal_hours || 0),
      overtime_hours:Number(existing.rows[0].final_overtime_hours || 0),
      travel_hours:Number(existing.rows[0].final_travel_hours || 0),
      standby_hours:Number(existing.rows[0].final_standby_hours || 0),
      underground_allowance:existing.rows[0].underground_allowance
    }
  }
  const { schedule, calculation } = await calculateDay(client, userId, date)
  if (!calculation.lines.length && (!existing.rows[0] || existing.rows[0].status === "DRAFT")) {
    if (existing.rows[0]?.status === "DRAFT") {
      await client.query(`DELETE FROM atec.tbldailytimesheet t
        WHERE t.timesheetid=$1
          AND NOT EXISTS (SELECT 1 FROM atec.tbltimeentry entry
            WHERE entry.user_id=t.user_id AND entry.activity_date=t.timesheet_date)`, [existing.rows[0].timesheetid])
    }
    return { timesheet:null, ...calculation, schedule }
  }
  const header = await client.query(`
    INSERT INTO atec.tbldailytimesheet
      (user_id,timesheet_date,status,schedule_snapshot,calculated_normal_hours,calculated_overtime_hours,
       calculated_travel_hours,calculated_standby_hours,final_normal_hours,final_overtime_hours,
       final_travel_hours,final_standby_hours,underground_allowance,manager_user_id)
    SELECT $1::integer,$2::date,'DRAFT',$3::jsonb,$4::numeric,$5::numeric,$6::numeric,$7::numeric,
      $4::numeric,$5::numeric,$6::numeric,$7::numeric,$8::boolean,u.manager_user_id
    FROM atec.tblusers u WHERE u.userid=$1::integer
    ON CONFLICT (user_id,timesheet_date) DO UPDATE SET
      schedule_snapshot=EXCLUDED.schedule_snapshot,
      calculated_normal_hours=EXCLUDED.calculated_normal_hours,
      calculated_overtime_hours=EXCLUDED.calculated_overtime_hours,
      calculated_travel_hours=EXCLUDED.calculated_travel_hours,
      calculated_standby_hours=EXCLUDED.calculated_standby_hours,
      final_normal_hours=CASE WHEN atec.tbldailytimesheet.adjustment_reason='' THEN EXCLUDED.final_normal_hours ELSE atec.tbldailytimesheet.final_normal_hours END,
      final_overtime_hours=CASE WHEN atec.tbldailytimesheet.adjustment_reason='' THEN EXCLUDED.final_overtime_hours ELSE atec.tbldailytimesheet.final_overtime_hours END,
      final_travel_hours=CASE WHEN atec.tbldailytimesheet.adjustment_reason='' THEN EXCLUDED.final_travel_hours ELSE atec.tbldailytimesheet.final_travel_hours END,
      final_standby_hours=CASE WHEN atec.tbldailytimesheet.adjustment_reason='' THEN EXCLUDED.final_standby_hours ELSE atec.tbldailytimesheet.final_standby_hours END,
      underground_allowance=EXCLUDED.underground_allowance,
      manager_user_id=EXCLUDED.manager_user_id,
      updated_at=now()
    RETURNING *`, [
    userId, date, JSON.stringify(schedule), calculation.normal_hours, calculation.overtime_hours,
    calculation.travel_hours, calculation.standby_hours, calculation.underground_allowance
  ])
  const timesheet = header.rows[0]
  await client.query("DELETE FROM atec.tbldailytimesheetline WHERE timesheetid=$1", [timesheet.timesheetid])
  for (const line of calculation.lines) {
    await client.query(`
      INSERT INTO atec.tbldailytimesheetline
        (timesheetid,timeentryid,task_number,activity_type,started_at,ended_at,normal_hours,overtime_hours,
         worksheet_number,job_number,customer_name,brief_details,underground)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`, [
      timesheet.timesheetid, line.timeentryid, line.task_number, line.activity_type,
      line.started_at, line.ended_at, line.normal_hours, line.overtime_hours,
      line.jobcard_reference_snapshot, line.job_number_snapshot, line.customer_name_snapshot,
      line.brief_details, line.underground
    ])
  }
  return { timesheet, ...calculation, schedule }
}

async function assertJobCardAccess(client, user, jobcardid, { forUpdate = false } = {}) {
  if (!["ADMIN","MANAGER","INSPECTOR"].includes(user?.role)) {
    const error = new Error("Access denied")
    error.statusCode = 403
    throw error
  }
  const result = await client.query(`SELECT jobcardid,assigned_to_user_id,created_by_user_id
    FROM atec.tbljobcard WHERE jobcardid=$1${forUpdate ? " FOR UPDATE" : ""}`, [jobcardid])
  const card = result.rows[0]
  if (!card) {
    const error = new Error("Job card not found")
    error.statusCode = 404
    throw error
  }
  if (user.role === "INSPECTOR" && ![card.assigned_to_user_id,card.created_by_user_id].map(Number).includes(Number(user.user_id))) {
    const error = new Error("This job card is not assigned to you")
    error.statusCode = 403
    throw error
  }
  return card
}

async function copyJobCardTimeline(client, jobcardid, actorUserId) {
  const cardResult = await client.query(`
    SELECT j.*,c.clientname FROM atec.tbljobcard j JOIN atec.tblclients c ON c.clientid=j.clientid
    WHERE j.jobcardid=$1 FOR UPDATE`, [jobcardid])
  const card = cardResult.rows[0]
  if (!card) {
    const error = new Error("Job card not found")
    error.statusCode = 404
    throw error
  }
  if (!/^[0-9]+$/.test(String(card.customer_reference || ""))) throw badRequest("Enter the numeric Accelo Job Number before copying crew time.")
  const crewResult = await client.query(`
    SELECT user_id FROM atec.tbljobcardcrew WHERE jobcardid=$1 AND included_in_time=true
    UNION SELECT assigned_to_user_id FROM atec.tbljobcard WHERE jobcardid=$1 AND assigned_to_user_id IS NOT NULL`, [jobcardid])
  const segments = [
    ["TRAVEL",card.departed_at,card.arrived_at],
    ["STANDBY",card.arrived_at,card.work_started_at],
    ["WORK",card.work_started_at,card.work_completed_at],
    ["TRAVEL",card.work_completed_at,card.travel_completed_at]
  ].filter(([,start,end]) => start && end && new Date(end) > new Date(start))
  for (const member of crewResult.rows) {
    await client.query(`DELETE FROM atec.tbltimeentry WHERE jobcardid=$1 AND user_id=$2
      AND source IN ('JOB_CARD','COPIED_FROM_LEAD') AND employee_confirmed_at IS NULL`, [card.jobcardid,member.user_id])
    const affectedDates = new Set()
    for (const [type,start,end] of segments) {
      const activityDate = isoDate(start)
      affectedDates.add(activityDate)
      await client.query(`INSERT INTO atec.tbltimeentry
        (user_id,jobcardid,activity_date,activity_type,started_at,ended_at,customer_name_snapshot,
         job_number_snapshot,jobcard_reference_snapshot,brief_details,source,source_user_id)
        VALUES($1,$2,$3::date,$4,$5,$6,$7,$8,$9,$10,$11,$12)`, [
        member.user_id,card.jobcardid,activityDate,type,start,end,card.clientname,
        card.customer_reference,card.jobcard_reference,card.work_performed || card.reported_fault || card.job_type,
        Number(member.user_id) === Number(card.assigned_to_user_id) ? "JOB_CARD" : "COPIED_FROM_LEAD",actorUserId
      ])
    }
    for (const activityDate of affectedDates) {
      const rebuilt = await rebuildTimesheet(client,member.user_id,activityDate)
      await client.query(`UPDATE atec.tbldailytimesheet SET status='AWAITING_EMPLOYEE',returned_reason='',updated_at=now()
        WHERE timesheetid=$1 AND status IN ('DRAFT','RETURNED','AWAITING_EMPLOYEE')`, [rebuilt.timesheet.timesheetid])
    }
  }
  return { success:true, crew:crewResult.rowCount, segments:segments.length }
}

async function loadTimesheetPdfData(pool, timesheetId) {
  const result = await pool.query(`SELECT t.*,COALESCE(NULLIF(u.fullname,''),u.username) AS employee_name,
    u.employee_number,COALESCE(NULLIF(m.fullname,''),m.username) AS manager_name,
    COALESCE(json_agg(l ORDER BY l.task_number) FILTER (WHERE l.timesheetlineid IS NOT NULL),'[]') AS lines
    FROM atec.tbldailytimesheet t
    JOIN atec.tblusers u ON u.userid=t.user_id
    LEFT JOIN atec.tblusers m ON m.userid=t.manager_user_id
    LEFT JOIN atec.tbldailytimesheetline l ON l.timesheetid=t.timesheetid
    WHERE t.timesheetid=$1
    GROUP BY t.timesheetid,u.userid,m.userid`, [timesheetId])
  return result.rows[0] || null
}

async function loadAcceloReadiness(pool, jobcardid) {
  const cardResult = await pool.query(`SELECT j.jobcardid,j.jobcard_reference,j.customer_reference,j.job_type,j.status,
    j.clientid,j.accelo_email_sent_at,c.clientname
    FROM atec.tbljobcard j JOIN atec.tblclients c ON c.clientid=j.clientid
    WHERE j.jobcardid=$1`, [jobcardid])
  const card = cardResult.rows[0]
  if (!card) return null
  const crew = await pool.query(`SELECT DISTINCT crew.user_id,COALESCE(NULLIF(u.fullname,''),u.username) AS employee_name
    FROM atec.tbljobcardcrew crew JOIN atec.tblusers u ON u.userid=crew.user_id
    WHERE crew.jobcardid=$1 AND crew.included_in_time=true
    ORDER BY employee_name`, [jobcardid])
  const timesheets = await pool.query(`SELECT DISTINCT t.timesheetid,t.user_id,t.timesheet_date,t.status,
    COALESCE(NULLIF(u.fullname,''),u.username) AS employee_name
    FROM atec.tbltimeentry entry
    JOIN atec.tbldailytimesheet t ON t.user_id=entry.user_id AND t.timesheet_date=entry.activity_date
    JOIN atec.tblusers u ON u.userid=t.user_id
    WHERE entry.jobcardid=$1
    ORDER BY t.timesheet_date,t.user_id`, [jobcardid])
  const assets = await pool.query(`SELECT ja.assetid,COALESCE(NULLIF(a.assettagno,''),NULLIF(a.serialno,''),'Asset ' || ja.assetid::text) AS asset_name
    FROM atec.tbljobcardasset ja LEFT JOIN atec.tblasset a ON a.assetid=ja.assetid
    WHERE ja.jobcardid=$1 ORDER BY asset_name`, [jobcardid])
  const certificates = await pool.query(`SELECT DISTINCT i.testid,i.assetid,i.status,i.inspectiontype,
      CASE WHEN i.jobcardid=$1 THEN 'DIRECT_JOB_CARD' ELSE 'ACCELO_JOB_AND_ASSET' END AS link_source
    FROM atec.tblinspection i
    JOIN atec.tblasset a ON a.assetid=i.assetid
    WHERE COALESCE(i.record_status,'ACTIVE')='ACTIVE'
      AND (
        i.jobcardid=$1
        OR (
          i.jobcardid IS NULL
          AND NULLIF(TRIM(COALESCE(i.job_number,'')),'')=$2
          AND a.clientid=$3
          AND EXISTS (
            SELECT 1 FROM atec.tbljobcardasset selected
            WHERE selected.jobcardid=$1 AND selected.assetid=i.assetid
          )
        )
      )
    ORDER BY i.testid`, [jobcardid,String(card.customer_reference || "").trim(),card.clientid])
  const approvedStatuses = new Set(["MANAGER_APPROVED","HR_ACCEPTED","EXPORTED"])
  const missingCrew = crew.rows.filter(member => !timesheets.rows.some(sheet => Number(sheet.user_id) === Number(member.user_id)))
  const unapproved = timesheets.rows.filter(sheet => !approvedStatuses.has(sheet.status))
  const issues = []
  if (!["APPROVED","INVOICED"].includes(card.status)) issues.push("The Job Card must be approved.")
  if (!/^[0-9]+$/.test(String(card.customer_reference || ""))) issues.push("The Accelo Job Number is missing or invalid.")
  if (!crew.rows.length) issues.push("No Job Card crew has been recorded.")
  if (missingCrew.length) issues.push(`Missing timesheets: ${missingCrew.map(row => row.employee_name).join(", ")}.`)
  if (unapproved.length) issues.push(`Timesheets awaiting approval: ${unapproved.map(row => `${row.employee_name} (${row.status.replaceAll("_"," ")})`).join(", ")}.`)
  if (card.job_type === "INSPECTIONS") {
    if (!certificates.rows.length) issues.push("An Inspection Job Card must have at least one linked certificate.")
    const certifiedAssetIds = new Set(certificates.rows.map(row => Number(row.assetid)))
    const missingCertificates = assets.rows.filter(row => row.assetid && !certifiedAssetIds.has(Number(row.assetid)))
    if (missingCertificates.length) issues.push(`Missing certificates for Job Card equipment: ${missingCertificates.map(row => row.asset_name).join(", ")}.`)
  }
  return {
    card,
    recipient: /^[0-9]+$/.test(String(card.customer_reference || ""))
      ? `job+${card.customer_reference}@fb-cranes.accelo.com`
      : "",
    crew: crew.rows,
    assets: assets.rows,
    timesheets: timesheets.rows,
    certificates: certificates.rows,
    issues,
    ready: issues.length === 0
  }
}

function registerWorkforceRoutes(app, {
  pool,
  asyncRoute,
  pdfLimiter,
  emailLimiter,
  brandRoot,
  loadJobCard,
  createJobCardPdfBuffer,
  createCertificatePdfBuffer,
  getCertificateData,
  sendApplicationEmail,
  getMailConfigIssues,
  getMailErrorMessage,
  ExcelJS
}) {
  const router = express.Router()

  router.get("/employees", asyncRoute(async (req, res) => {
    if (!["ADMIN","MANAGER","INSPECTOR","HR"].includes(req.user.role)) return res.status(403).json({ error: "Access denied" })
    const includeHr = req.query.include_hr === "true" && ["ADMIN","HR"].includes(req.user.role)
    const scheduleScope = req.query.work_schedule_scope === "true"
    const values = []
    let managerScope = ""
    if (scheduleScope && req.user.role === "MANAGER") {
      values.push(req.user.user_id)
      managerScope = ` AND manager_user_id=$${values.length}`
    }
    const result = await pool.query(`
      SELECT userid AS user_id,COALESCE(NULLIF(fullname,''),username) AS full_name,role,manager_user_id,employee_number
      FROM atec.tblusers
      WHERE COALESCE(is_active,true)=true AND (role IN ('ADMIN','MANAGER','INSPECTOR','ASSISTANT')${includeHr ? " OR role='HR'" : ""})${managerScope}
      ORDER BY COALESCE(NULLIF(fullname,''),username)`, values)
    res.json(result.rows)
  }))

  router.get("/job-cards/:id/crew", asyncRoute(async (req, res) => {
    await assertJobCardAccess(pool, req.user, req.params.id)
    const result = await pool.query(`
      SELECT crew.*,COALESCE(NULLIF(u.fullname,''),u.username) AS full_name,u.role
      FROM atec.tbljobcardcrew crew JOIN atec.tblusers u ON u.userid=crew.user_id
      WHERE crew.jobcardid=$1 ORDER BY CASE crew.crew_role WHEN 'LEAD_TECHNICIAN' THEN 0 ELSE 1 END,full_name`, [req.params.id])
    res.json(result.rows)
  }))

  router.put("/job-cards/:id/crew", asyncRoute(async (req, res) => {
    await assertJobCardAccess(pool, req.user, req.params.id)
    const crew = Array.isArray(req.body?.crew) ? req.body.crew : []
    if (crew.some(row => !Number(row.user_id) || !CREW_ROLES.has(String(row.crew_role)))) throw badRequest("Select valid crew members and roles.")
    const client = await pool.connect()
    try {
      await client.query("BEGIN")
      await client.query("DELETE FROM atec.tbljobcardcrew WHERE jobcardid=$1", [req.params.id])
      for (const row of crew) {
        await client.query(`INSERT INTO atec.tbljobcardcrew(jobcardid,user_id,crew_role,included_in_time,added_by_user_id)
          VALUES($1,$2,$3,$4,$5)`, [req.params.id,row.user_id,row.crew_role,row.included_in_time !== false,req.user.user_id])
      }
      await client.query("COMMIT")
      res.json({ success: true, count: crew.length })
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {})
      throw error
    } finally {
      client.release()
    }
  }))

  router.post("/job-cards/:id/copy-timeline", asyncRoute(async (req, res) => {
    const client = await pool.connect()
    try {
      await client.query("BEGIN")
      await assertJobCardAccess(client, req.user, req.params.id, { forUpdate:true })
      const result = await copyJobCardTimeline(client, req.params.id, req.user.user_id)
      await client.query("COMMIT")
      res.json(result)
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {})
      throw error
    } finally {
      client.release()
    }
  }))

  router.get("/my-day", asyncRoute(async (req, res) => {
    const date = req.query.date || isoDate()
    const requestedUserId = Number(req.query.user_id || req.user.user_id)
    if (requestedUserId !== Number(req.user.user_id) && !["ADMIN","MANAGER","HR"].includes(req.user.role)) return res.status(403).json({ error:"Access denied" })
    const client = await pool.connect()
    try {
      const data = await rebuildTimesheet(client,requestedUserId,date)
      res.json(data)
    } finally { client.release() }
  }))

  router.post("/time-entries", asyncRoute(async (req, res) => {
    const userId = Number(req.body.user_id || req.user.user_id)
    if (userId !== Number(req.user.user_id) && !["ADMIN","MANAGER","HR"].includes(req.user.role)) return res.status(403).json({ error:"Access denied" })
    if (!ACTIVITY_TYPES.has(String(req.body.activity_type))) throw badRequest("Select a valid activity type.")
    const jobNumber = String(req.body.job_number || "").trim()
    if (JOB_RELATED_ACTIVITIES.has(String(req.body.activity_type)) && !/^[0-9]+$/.test(jobNumber)) {
      throw badRequest("Enter the numeric Accelo Job Number for job-related time.")
    }
    if (jobNumber && !/^[0-9]+$/.test(jobNumber)) throw badRequest("Accelo Job Number may contain numeric digits only.")
    const startedAt = new Date(req.body.started_at)
    const endedAt = new Date(req.body.ended_at)
    if (Number.isNaN(startedAt.getTime()) || Number.isNaN(endedAt.getTime()) || endedAt <= startedAt) {
      throw badRequest("Enter valid start and end times; end time must be after start time.")
    }
    const locked = await pool.query(`SELECT status FROM atec.tbldailytimesheet
      WHERE user_id=$1 AND timesheet_date=$2::date
        AND status IN ('EMPLOYEE_SUBMITTED','MANAGER_APPROVED','HR_ACCEPTED','EXPORTED')`, [
      userId,req.body.activity_date || isoDate(req.body.started_at)
    ])
    if (locked.rows[0] && !["ADMIN","MANAGER","HR"].includes(req.user.role)) {
      throw badRequest("This timesheet has already been submitted. Ask your manager to return it before changing time.")
    }
    const reason = String(req.body.adjustment_reason || "").trim()
    if (req.body.source_timeentryid && !reason) throw badRequest("Enter a reason for changing recorded time.")
    let linkedJob = null
    if (jobNumber) {
      const linked = await pool.query(`SELECT j.jobcardid,j.jobcard_reference,j.customer_reference,c.clientname
        FROM atec.tbljobcard j JOIN atec.tblclients c ON c.clientid=j.clientid
        WHERE j.customer_reference=$1
        ORDER BY j.updated_at DESC,j.jobcardid DESC LIMIT 1`, [jobNumber])
      linkedJob = linked.rows[0] || null
    }
    const result = await pool.query(`INSERT INTO atec.tbltimeentry
      (user_id,jobcardid,activity_date,activity_type,started_at,ended_at,brief_details,underground,source,source_user_id,
       adjustment_reason,customer_name_snapshot,job_number_snapshot,jobcard_reference_snapshot)
      VALUES($1,$2,$3::date,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`, [
      userId,linkedJob?.jobcardid || req.body.jobcardid || null,req.body.activity_date || isoDate(req.body.started_at),req.body.activity_type,
      req.body.started_at,req.body.ended_at,String(req.body.brief_details || ""),req.body.underground === true,
      userId === Number(req.user.user_id) ? "EMPLOYEE" : req.user.role,req.user.user_id,reason,
      linkedJob?.clientname || String(req.body.customer_name || ""),jobNumber,
      linkedJob?.jobcard_reference || String(req.body.jobcard_reference || "")
    ])
    const client = await pool.connect()
    try { await rebuildTimesheet(client,userId,result.rows[0].activity_date) } finally { client.release() }
    res.status(201).json(result.rows[0])
  }))

  router.put("/time-entries/:entryId", asyncRoute(async (req, res) => {
    const reason = String(req.body.reason || "").trim()
    if (reason.length < 5) throw badRequest("Enter a clear reason of at least 5 characters for changing your time.")
    const startedAt = new Date(req.body.started_at)
    const endedAt = new Date(req.body.ended_at)
    if (Number.isNaN(startedAt.getTime()) || Number.isNaN(endedAt.getTime()) || endedAt <= startedAt) {
      throw badRequest("Enter valid start and end times; end time must be after start time.")
    }
    if (endedAt - startedAt > 24 * 60 * 60 * 1000) throw badRequest("A time entry cannot exceed 24 hours.")
    const client = await pool.connect()
    try {
      await client.query("BEGIN")
      const entryResult = await client.query(`SELECT entry.*,sheet.timesheetid,sheet.status
        FROM atec.tbltimeentry entry LEFT JOIN atec.tbldailytimesheet sheet
          ON sheet.user_id=entry.user_id AND sheet.timesheet_date=entry.activity_date
        WHERE entry.timeentryid=$1 AND entry.user_id=$2 FOR UPDATE OF entry`, [req.params.entryId,req.user.user_id])
      const entry = entryResult.rows[0]
      if (!entry) {
        const error = new Error("Time entry not found")
        error.statusCode = 404
        throw error
      }
      if (entry.status && !["DRAFT","AWAITING_EMPLOYEE","RETURNED"].includes(entry.status)) {
        const error = new Error("Submitted or approved time cannot be changed by the employee.")
        error.statusCode = 409
        throw error
      }
      const activityDate = isoDate(startedAt)
      await client.query(`UPDATE atec.tbltimeentry SET activity_date=$1::date,started_at=$2,ended_at=$3,
        adjustment_reason=$4,source='EMPLOYEE',source_user_id=$5,updated_at=now()
        WHERE timeentryid=$6`, [activityDate,req.body.started_at,req.body.ended_at,reason,req.user.user_id,entry.timeentryid])
      await rebuildTimesheet(client,req.user.user_id,entry.activity_date)
      if (activityDate !== String(entry.activity_date).slice(0,10)) await rebuildTimesheet(client,req.user.user_id,activityDate)
      if (entry.timesheetid) await client.query(`INSERT INTO atec.tbltimesheetaudit(timesheetid,actor_user_id,action,details)
        VALUES($1,$2,'EMPLOYEE_TIME_EDIT',$3)`, [entry.timesheetid,req.user.user_id,JSON.stringify({
          timeentryid:entry.timeentryid,reason,before:{started_at:entry.started_at,ended_at:entry.ended_at},after:{started_at:req.body.started_at,ended_at:req.body.ended_at}
        })])
      await client.query("COMMIT")
      res.json({ success:true })
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {})
      throw error
    } finally { client.release() }
  }))

  router.delete("/time-entries/:entryId", asyncRoute(async (req, res) => {
    const reason = String(req.body?.reason || "").trim()
    if (reason.length < 5) throw badRequest("Enter a clear reason of at least 5 characters for deleting your time entry.")
    const client = await pool.connect()
    try {
      await client.query("BEGIN")
      const entryResult = await client.query(`SELECT entry.*,sheet.timesheetid,sheet.status
        FROM atec.tbltimeentry entry LEFT JOIN atec.tbldailytimesheet sheet
          ON sheet.user_id=entry.user_id AND sheet.timesheet_date=entry.activity_date
        WHERE entry.timeentryid=$1 AND entry.user_id=$2 FOR UPDATE OF entry`, [req.params.entryId,req.user.user_id])
      const entry = entryResult.rows[0]
      if (!entry) {
        const error = new Error("Time entry not found")
        error.statusCode = 404
        throw error
      }
      if (entry.status && !["DRAFT","AWAITING_EMPLOYEE","RETURNED"].includes(entry.status)) {
        const error = new Error("Submitted or approved time cannot be deleted by the employee.")
        error.statusCode = 409
        throw error
      }
      await client.query("DELETE FROM atec.tbltimeentry WHERE timeentryid=$1", [entry.timeentryid])
      await rebuildTimesheet(client,req.user.user_id,entry.activity_date)
      if (entry.timesheetid) await client.query(`INSERT INTO atec.tbltimesheetaudit(timesheetid,actor_user_id,action,details)
        VALUES($1,$2,'EMPLOYEE_TIME_DELETE',$3)`, [entry.timesheetid,req.user.user_id,JSON.stringify({
          timeentryid:entry.timeentryid,reason,deleted:{activity_type:entry.activity_type,started_at:entry.started_at,ended_at:entry.ended_at,job_number:entry.job_number_snapshot}
        })])
      await client.query("COMMIT")
      res.json({ success:true })
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {})
      throw error
    } finally { client.release() }
  }))

  router.post("/timesheets/:date/submit", asyncRoute(async (req, res) => {
    const client = await pool.connect()
    try {
      await client.query("BEGIN")
      const data = await rebuildTimesheet(client,req.user.user_id,req.params.date)
      if (!data.lines.length) throw badRequest("Add at least one time entry before submitting.")
      const result = await client.query(`UPDATE atec.tbldailytimesheet SET status='EMPLOYEE_SUBMITTED',
        employee_submitted_at=now(),returned_reason='',updated_at=now() WHERE timesheetid=$1 RETURNING *`, [data.timesheet.timesheetid])
      await client.query(`INSERT INTO atec.tbltimesheetaudit(timesheetid,actor_user_id,action)
        VALUES($1,$2,'EMPLOYEE_SUBMITTED')`, [data.timesheet.timesheetid,req.user.user_id])
      await client.query("COMMIT")
      res.json(result.rows[0])
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {})
      throw error
    } finally { client.release() }
  }))

  router.get("/approvals", asyncRoute(async (req, res) => {
    if (![...["ADMIN","MANAGER","HR"]].includes(req.user.role)) return res.status(403).json({ error:"Access denied" })
    const values = []
    let where = "WHERE t.status IN ('EMPLOYEE_SUBMITTED','MANAGER_APPROVED','RETURNED')"
    if (req.user.role === "MANAGER") {
      values.push(req.user.user_id)
      where += ` AND u.manager_user_id=$${values.length}`
    }
    const result = await pool.query(`SELECT t.*,t.timesheet_date::text AS timesheet_date,
      COALESCE(NULLIF(u.fullname,''),u.username) AS employee_name,u.employee_number
      FROM atec.tbldailytimesheet t JOIN atec.tblusers u ON u.userid=t.user_id ${where}
      ORDER BY t.timesheet_date DESC,employee_name`, values)
    res.json(result.rows)
  }))

  router.get("/timesheets/:id/manager-edit", asyncRoute(async (req, res) => {
    if (!["ADMIN","MANAGER","HR"].includes(req.user.role)) return res.status(403).json({ error:"Access denied" })
    const values = [req.params.id]
    let managerScope = ""
    if (req.user.role === "MANAGER") {
      values.push(req.user.user_id)
      managerScope = ` AND u.manager_user_id=$${values.length} AND t.manager_user_id=$${values.length}`
    }
    const sheetResult = await pool.query(`SELECT t.timesheetid,t.user_id,t.timesheet_date,t.status,
      COALESCE(NULLIF(u.fullname,''),u.username) AS employee_name
      FROM atec.tbldailytimesheet t JOIN atec.tblusers u ON u.userid=t.user_id
      WHERE t.timesheetid=$1${managerScope}`, values)
    const sheet = sheetResult.rows[0]
    if (!sheet) return res.status(404).json({ error:"Timesheet not found or not assigned to you" })
    const editableStatuses = req.user.role === "MANAGER"
      ? ["EMPLOYEE_SUBMITTED"]
      : ["EMPLOYEE_SUBMITTED","MANAGER_APPROVED","RETURNED"]
    if (!editableStatuses.includes(sheet.status)) {
      return res.status(409).json({ error:"This timesheet is not at an editable stage. HR-accepted and exported records remain locked." })
    }
    const entries = await pool.query(`SELECT timeentryid,activity_type,started_at,ended_at,
      customer_name_snapshot,job_number_snapshot,brief_details,adjustment_reason
      FROM atec.tbltimeentry WHERE user_id=$1 AND activity_date=$2::date ORDER BY started_at,timeentryid`,
    [sheet.user_id,sheet.timesheet_date])
    const audits = await pool.query(`SELECT audit.created_at,audit.details,
      COALESCE(NULLIF(actor.fullname,''),actor.username) AS actor_name
      FROM atec.tbltimesheetaudit audit LEFT JOIN atec.tblusers actor ON actor.userid=audit.actor_user_id
      WHERE audit.timesheetid=$1 AND audit.action IN ('MANAGER_TIME_EDIT','MANAGER_TIME_DELETE')
      ORDER BY audit.created_at DESC`, [sheet.timesheetid])
    res.json({ timesheet:sheet, entries:entries.rows, audits:audits.rows })
  }))

  router.put("/timesheets/:id/time-entries/:entryId", asyncRoute(async (req, res) => {
    if (!["ADMIN","MANAGER","HR"].includes(req.user.role)) return res.status(403).json({ error:"Access denied" })
    const reason = String(req.body.reason || "").trim()
    if (reason.length < 5) throw badRequest("Enter a clear reason of at least 5 characters for changing the employee's time.")
    const startedAt = new Date(req.body.started_at)
    const endedAt = new Date(req.body.ended_at)
    if (Number.isNaN(startedAt.getTime()) || Number.isNaN(endedAt.getTime()) || endedAt <= startedAt) {
      throw badRequest("Enter valid start and end times; end time must be after start time.")
    }
    if (endedAt - startedAt > 24 * 60 * 60 * 1000) throw badRequest("A time entry cannot exceed 24 hours.")

    const client = await pool.connect()
    try {
      await client.query("BEGIN")
      const values = [req.params.id,req.params.entryId]
      let managerScope = ""
      if (req.user.role === "MANAGER") {
        values.push(req.user.user_id)
        managerScope = ` AND u.manager_user_id=$${values.length} AND t.manager_user_id=$${values.length}`
      }
      const result = await client.query(`SELECT t.timesheetid,t.user_id,t.timesheet_date,t.status,
        entry.timeentryid,entry.started_at,entry.ended_at
        FROM atec.tbldailytimesheet t
        JOIN atec.tblusers u ON u.userid=t.user_id
        JOIN atec.tbltimeentry entry ON entry.user_id=t.user_id AND entry.activity_date=t.timesheet_date
        WHERE t.timesheetid=$1 AND entry.timeentryid=$2${managerScope} FOR UPDATE`, values)
      const current = result.rows[0]
      if (!current) {
        const error = new Error("Time entry not found or not assigned to you")
        error.statusCode = 404
        throw error
      }
      const editableStatuses = req.user.role === "MANAGER"
        ? ["EMPLOYEE_SUBMITTED"]
        : ["EMPLOYEE_SUBMITTED","MANAGER_APPROVED","RETURNED"]
      if (!editableStatuses.includes(current.status)) {
        const error = new Error("This timesheet is not at an editable stage. HR-accepted and exported records remain locked.")
        error.statusCode = 409
        throw error
      }
      if (new Date(current.started_at).getTime() === startedAt.getTime() &&
          new Date(current.ended_at).getTime() === endedAt.getTime()) {
        throw badRequest("Change the start or end time before saving.")
      }

      const before = { started_at:current.started_at, ended_at:current.ended_at }
      await client.query(`UPDATE atec.tbltimeentry SET started_at=$1,ended_at=$2,
        adjustment_reason=$3,updated_at=now() WHERE timeentryid=$4`,
      [req.body.started_at,req.body.ended_at,reason,current.timeentryid])
      await rebuildTimesheet(client,current.user_id,current.timesheet_date,{ force:true })
      await client.query(`INSERT INTO atec.tbltimesheetaudit(timesheetid,actor_user_id,action,details)
        VALUES($1,$2,'MANAGER_TIME_EDIT',$3::jsonb)`, [current.timesheetid,req.user.user_id,JSON.stringify({
        timeentryid:current.timeentryid,
        reason,
        before,
        after:{ started_at:req.body.started_at, ended_at:req.body.ended_at }
      })])
      await client.query("COMMIT")
      res.json({ success:true, timesheetid:current.timesheetid, timeentryid:current.timeentryid })
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {})
      throw error
    } finally { client.release() }
  }))

  router.delete("/timesheets/:id/time-entries/:entryId", asyncRoute(async (req, res) => {
    if (!["ADMIN","MANAGER","HR"].includes(req.user.role)) return res.status(403).json({ error:"Access denied" })
    const reason = String(req.body?.reason || "").trim()
    if (reason.length < 5) throw badRequest("Enter a clear reason of at least 5 characters for deleting the employee's time entry.")
    const client = await pool.connect()
    try {
      await client.query("BEGIN")
      const values = [req.params.id,req.params.entryId]
      let managerScope = ""
      if (req.user.role === "MANAGER") {
        values.push(req.user.user_id)
        managerScope = ` AND u.manager_user_id=$${values.length} AND t.manager_user_id=$${values.length}`
      }
      const result = await client.query(`SELECT t.timesheetid,t.user_id,t.timesheet_date,t.status,
        entry.timeentryid,entry.activity_type,entry.started_at,entry.ended_at,entry.job_number_snapshot
        FROM atec.tbldailytimesheet t
        JOIN atec.tblusers u ON u.userid=t.user_id
        JOIN atec.tbltimeentry entry ON entry.user_id=t.user_id AND entry.activity_date=t.timesheet_date
        WHERE t.timesheetid=$1 AND entry.timeentryid=$2${managerScope} FOR UPDATE OF entry`, values)
      const current = result.rows[0]
      if (!current) {
        const error = new Error("Time entry not found or not assigned to you")
        error.statusCode = 404
        throw error
      }
      const editableStatuses = req.user.role === "MANAGER"
        ? ["EMPLOYEE_SUBMITTED"]
        : ["EMPLOYEE_SUBMITTED","MANAGER_APPROVED","RETURNED"]
      if (!editableStatuses.includes(current.status)) {
        const error = new Error("This timesheet is not at an editable stage. HR-accepted and exported records remain locked.")
        error.statusCode = 409
        throw error
      }
      await client.query("DELETE FROM atec.tbltimeentry WHERE timeentryid=$1", [current.timeentryid])
      await rebuildTimesheet(client,current.user_id,current.timesheet_date,{ force:true })
      await client.query(`INSERT INTO atec.tbltimesheetaudit(timesheetid,actor_user_id,action,details)
        VALUES($1,$2,'MANAGER_TIME_DELETE',$3::jsonb)`, [current.timesheetid,req.user.user_id,JSON.stringify({
        timeentryid:current.timeentryid,reason,actor_role:req.user.role,
        deleted:{ activity_type:current.activity_type,started_at:current.started_at,ended_at:current.ended_at,job_number:current.job_number_snapshot }
      })])
      await client.query("COMMIT")
      res.json({ success:true,timesheetid:current.timesheetid,timeentryid:current.timeentryid })
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {})
      throw error
    } finally { client.release() }
  }))

  router.get("/timesheets/history", asyncRoute(async (req, res) => {
    const values = []
    const where = []
    const requestedUserId = Number(req.query.user_id || 0)
    if (req.query.mine === "true" || ["ASSISTANT","INSPECTOR"].includes(req.user.role)) {
      values.push(req.user.user_id)
      where.push(`t.user_id=$${values.length}`)
    } else if (req.user.role === "MANAGER") {
      values.push(req.user.user_id)
      where.push(`u.manager_user_id=$${values.length}`)
    } else if (!["ADMIN","HR"].includes(req.user.role)) {
      return res.status(403).json({ error:"Access denied" })
    } else if (requestedUserId) {
      values.push(requestedUserId)
      where.push(`t.user_id=$${values.length}`)
    }
    if (req.query.date_from) {
      values.push(req.query.date_from)
      where.push(`t.timesheet_date >= $${values.length}::date`)
    }
    if (req.query.date_to) {
      values.push(req.query.date_to)
      where.push(`t.timesheet_date <= $${values.length}::date`)
    }
    if (req.query.status) {
      values.push(String(req.query.status).toUpperCase())
      where.push(`t.status=$${values.length}`)
    }
    if (req.query.job_number) {
      values.push(String(req.query.job_number).trim())
      where.push(`EXISTS (SELECT 1 FROM atec.tbldailytimesheetline line
        WHERE line.timesheetid=t.timesheetid AND line.job_number=$${values.length})`)
    }
    values.push(Math.min(500,Math.max(1,Number(req.query.limit || 100))))
    const limitParam = `$${values.length}`
    const result = await pool.query(`SELECT t.*,t.timesheet_date::text AS timesheet_date,
      COALESCE(NULLIF(u.fullname,''),u.username) AS employee_name,
      u.employee_number,COALESCE(NULLIF(m.fullname,''),m.username) AS manager_name,
      COALESCE((SELECT string_agg(DISTINCT NULLIF(line.job_number,''),', ' ORDER BY NULLIF(line.job_number,''))
        FROM atec.tbldailytimesheetline line WHERE line.timesheetid=t.timesheetid),'') AS job_numbers,
      COALESCE((SELECT count(*)::int FROM atec.tbldailytimesheetline line WHERE line.timesheetid=t.timesheetid),0) AS line_count
      FROM atec.tbldailytimesheet t
      JOIN atec.tblusers u ON u.userid=t.user_id
      LEFT JOIN atec.tblusers m ON m.userid=t.manager_user_id
      ${where.length ? `WHERE ${where.join(" AND ")}` : ""}
      ORDER BY t.timesheet_date DESC,t.timesheetid DESC LIMIT ${limitParam}`, values)
    res.json(result.rows)
  }))

  router.get("/payroll-export.xlsx", asyncRoute(async (req, res) => {
    if (!["ADMIN","HR","MANAGER"].includes(req.user.role)) return res.status(403).json({ error:"Access denied" })
    const dateFrom = String(req.query.date_from || "")
    const dateTo = String(req.query.date_to || "")
    if (!/^\d{4}-\d{2}-\d{2}$/.test(dateFrom) || !/^\d{4}-\d{2}-\d{2}$/.test(dateTo)) {
      throw badRequest("Select a valid payroll start and end date.")
    }
    const fromDate = new Date(`${dateFrom}T00:00:00Z`)
    const toDate = new Date(`${dateTo}T00:00:00Z`)
    const spanDays = (toDate - fromDate) / 86400000
    if (spanDays < 0 || spanDays > 366) throw badRequest("Payroll export period must be between 1 and 367 days.")
    const employeeIds = String(req.query.user_ids || "").split(",").filter(Boolean).map(Number)
    if (employeeIds.some(value => !Number.isInteger(value) || value <= 0) || employeeIds.length > 500) {
      throw badRequest("Select valid employees for the payroll export.")
    }
    const statuses = req.query.include_exported === "true" ? ["HR_ACCEPTED","EXPORTED"] : ["HR_ACCEPTED"]
    const values = [dateFrom,dateTo,statuses]
    const where = ["t.timesheet_date BETWEEN $1::date AND $2::date","t.status=ANY($3::text[])"]
    if (req.user.role === "MANAGER") {
      values.push(req.user.user_id)
      where.push(`u.manager_user_id=$${values.length}`)
    }
    if (employeeIds.length) {
      values.push(employeeIds)
      where.push(`t.user_id=ANY($${values.length}::int[])`)
    }
    const dailyResult = await pool.query(`SELECT t.timesheetid,t.timesheet_date,t.status,t.underground_allowance,
      t.final_normal_hours::float8 AS normal_hours,t.final_overtime_hours::float8 AS overtime_hours,
      t.final_travel_hours::float8 AS travel_hours,t.final_standby_hours::float8 AS standby_hours,
      u.userid AS user_id,u.employee_number,u.role,COALESCE(NULLIF(u.fullname,''),u.username) AS employee_name,
      COALESCE(NULLIF(m.fullname,''),m.username) AS manager_name,
      COALESCE((SELECT string_agg(DISTINCT NULLIF(line.job_number,''),', ' ORDER BY NULLIF(line.job_number,''))
        FROM atec.tbldailytimesheetline line WHERE line.timesheetid=t.timesheetid),'') AS job_numbers
      FROM atec.tbldailytimesheet t JOIN atec.tblusers u ON u.userid=t.user_id
      LEFT JOIN atec.tblusers m ON m.userid=t.manager_user_id
      WHERE ${where.join(" AND ")}
      ORDER BY employee_name,t.timesheet_date`, values)
    const timesheetIds = dailyResult.rows.map(row => row.timesheetid)
    const detailResult = timesheetIds.length ? await pool.query(`SELECT t.timesheet_date,u.employee_number,
      COALESCE(NULLIF(u.fullname,''),u.username) AS employee_name,line.job_number,line.worksheet_number,
      line.customer_name,line.activity_type,line.started_at,line.ended_at,line.normal_hours::float8 AS normal_hours,
      line.overtime_hours::float8 AS overtime_hours,line.underground,line.brief_details
      FROM atec.tbldailytimesheetline line JOIN atec.tbldailytimesheet t ON t.timesheetid=line.timesheetid
      JOIN atec.tblusers u ON u.userid=t.user_id WHERE line.timesheetid=ANY($1::int[])
      ORDER BY employee_name,t.timesheet_date,line.started_at,line.task_number`, [timesheetIds]) : { rows:[] }
    const grouped = new Map()
    dailyResult.rows.forEach(row => {
      const current = grouped.get(row.user_id) || {
        employee_number:row.employee_number,employee_name:row.employee_name,role:row.role,
        normal_hours:0,overtime_hours:0,travel_hours:0,standby_hours:0,underground_days:0,timesheet_days:0,jobs:new Set()
      }
      current.normal_hours += Number(row.normal_hours || 0)
      current.overtime_hours += Number(row.overtime_hours || 0)
      current.travel_hours += Number(row.travel_hours || 0)
      current.standby_hours += Number(row.standby_hours || 0)
      current.underground_days += row.underground_allowance ? 1 : 0
      current.timesheet_days += 1
      String(row.job_numbers || "").split(",").map(value => value.trim()).filter(Boolean).forEach(value => current.jobs.add(value))
      grouped.set(row.user_id,current)
    })
    const summaryRows = [...grouped.values()].map(row => ({ ...row,job_numbers:[...row.jobs].sort().join(", ") }))
    const workbook = await createPayrollWorkbook(ExcelJS, {
      summaryRows,dailyRows:dailyResult.rows,detailRows:detailResult.rows,dateFrom,dateTo,
      generatedBy:req.user.full_name || req.user.username || req.user.role,statuses
    })
    const buffer = await workbook.xlsx.writeBuffer()
    const filename = `ATEC-Payroll-${dateFrom}-to-${dateTo}.xlsx`
    res.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    res.setHeader("Content-Disposition",`attachment; filename="${filename}"`)
    res.send(Buffer.from(buffer))
  }))

  router.post("/timesheets/:id/action", asyncRoute(async (req, res) => {
    const action = String(req.body.action || "")
    const reason = String(req.body.reason || "").trim()
    const allowed = req.user.role === "ADMIN"
      ? new Set(["APPROVE","ACCEPT","RETURN","EXPORT"])
      : req.user.role === "MANAGER"
        ? new Set(["APPROVE","RETURN"])
        : req.user.role === "HR"
          ? new Set(["ACCEPT","RETURN","EXPORT"])
          : new Set()
    if (!allowed.has(action)) return res.status(403).json({ error:"Access denied" })
    if (action === "RETURN" && !reason) throw badRequest("Enter a reason for returning the timesheet.")
    const transitions = {
      APPROVE:["MANAGER_APPROVED","manager_approved_at","manager_user_id"],
      ACCEPT:["HR_ACCEPTED","hr_accepted_at","hr_user_id"],
      EXPORT:["EXPORTED","exported_at",null],
      RETURN:["RETURNED",null,null]
    }
    const [status,dateColumn,userColumn] = transitions[action]
    const expectedStatuses = {
      APPROVE: req.user.role === "ADMIN" ? ["EMPLOYEE_SUBMITTED","RETURNED"] : ["EMPLOYEE_SUBMITTED"],
      ACCEPT: ["MANAGER_APPROVED"],
      EXPORT: ["HR_ACCEPTED"],
      RETURN: req.user.role === "MANAGER" ? ["EMPLOYEE_SUBMITTED"] : ["EMPLOYEE_SUBMITTED","MANAGER_APPROVED","HR_ACCEPTED"]
    }[action]
    const updates = ["status=$1","returned_reason=$2","updated_at=now()"]
    if (dateColumn) updates.push(`${dateColumn}=now()`)
    if (userColumn) updates.push(`${userColumn}=$3`)
    const params = userColumn ? [status,reason,req.user.user_id,req.params.id] : [status,reason,req.params.id]
    const idParam = `$${params.length}`
    params.push(expectedStatuses)
    const stateParam = `$${params.length}`
    let managerScope = ""
    if (req.user.role === "MANAGER") {
      params.push(req.user.user_id)
      managerScope = ` AND manager_user_id=$${params.length}`
    }
    const result = await pool.query(`UPDATE atec.tbldailytimesheet SET ${updates.join(",")}
      WHERE timesheetid=${idParam} AND status=ANY(${stateParam}::text[])${managerScope} RETURNING *`, params)
    if (!result.rows[0]) return res.status(409).json({ error:"The timesheet is not in the correct stage for this action, or it is not assigned to you." })
    await pool.query(`INSERT INTO atec.tbltimesheetaudit(timesheetid,actor_user_id,action,details)
      VALUES($1,$2,$3,$4)`, [req.params.id,req.user.user_id,action,JSON.stringify({reason})])
    res.json(result.rows[0])
  }))

  router.get("/schedules/:userId", asyncRoute(async (req, res) => {
    if (!canManageWorkSchedules(req.user) && Number(req.params.userId) !== Number(req.user.user_id)) return res.status(403).json({ error:"Access denied" })
    if (req.user.role === "MANAGER") await assertWorkScheduleEmployeeAccess(pool,req.user,req.params.userId)
    const result = await pool.query(`SELECT s.*,s.effective_from::text AS effective_from,s.effective_to::text AS effective_to,
      COALESCE(json_agg(d ORDER BY d.weekday) FILTER (WHERE d.scheduledayid IS NOT NULL),'[]') AS days
      FROM atec.tblworkschedule s LEFT JOIN atec.tblworkscheduleday d ON d.scheduleid=s.scheduleid
      WHERE s.employee_user_id=$1 GROUP BY s.scheduleid ORDER BY s.effective_from DESC`, [req.params.userId])
    res.json(result.rows)
  }))

  router.post("/schedules", asyncRoute(async (req, res) => {
    if (!canManageWorkSchedules(req.user)) return res.status(403).json({ error:"Access denied" })
    await assertWorkScheduleEmployeeAccess(pool,req.user,req.body.employee_user_id)
    const days = Array.isArray(req.body.days) ? req.body.days : []
    const client = await pool.connect()
    try {
      await client.query("BEGIN")
      const result = await client.query(`INSERT INTO atec.tblworkschedule
        (schedule_name,employee_user_id,effective_from,effective_to,travel_treatment,rounding_minutes,created_by_user_id)
        VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`, [
        req.body.schedule_name,req.body.employee_user_id,req.body.effective_from,req.body.effective_to || null,
        req.body.travel_treatment || "SPLIT_BY_SCHEDULE",req.body.rounding_minutes || 1,req.user.user_id
      ])
      for (const day of days) await client.query(`INSERT INTO atec.tblworkscheduleday
        (scheduleid,weekday,normal_start,normal_end,unpaid_break_minutes,is_overtime_day)
        VALUES($1,$2,$3,$4,$5,$6)`, [
        result.rows[0].scheduleid,day.weekday,day.normal_start || null,day.normal_end || null,
        day.unpaid_break_minutes || 0,day.is_overtime_day === true
      ])
      await client.query("COMMIT")
      res.status(201).json(result.rows[0])
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {})
      throw error
    } finally { client.release() }
  }))

  router.put("/schedules/:id", asyncRoute(async (req, res) => {
    if (!canManageWorkSchedules(req.user)) return res.status(403).json({ error:"Access denied" })
    const owner = await pool.query("SELECT employee_user_id FROM atec.tblworkschedule WHERE scheduleid=$1",[req.params.id])
    if (!owner.rows[0]) return res.status(404).json({ error:"Work schedule not found" })
    await assertWorkScheduleEmployeeAccess(pool,req.user,owner.rows[0].employee_user_id)
    const days = Array.isArray(req.body.days) ? req.body.days : []
    if (!req.body.schedule_name || !req.body.effective_from || days.some(day => !Number.isInteger(Number(day.weekday)))) {
      throw badRequest("Enter a schedule name, effective date and valid working days.")
    }
    const client = await pool.connect()
    try {
      await client.query("BEGIN")
      const result = await client.query(`UPDATE atec.tblworkschedule SET schedule_name=$1,effective_from=$2,
        effective_to=$3,travel_treatment=$4,rounding_minutes=$5
        WHERE scheduleid=$6 RETURNING *`, [
        String(req.body.schedule_name).trim(),req.body.effective_from,req.body.effective_to || null,
        req.body.travel_treatment || "SPLIT_BY_SCHEDULE",req.body.rounding_minutes || 1,req.params.id
      ])
      if (!result.rows[0]) {
        const error = new Error("Work schedule not found")
        error.statusCode = 404
        throw error
      }
      await client.query("DELETE FROM atec.tblworkscheduleday WHERE scheduleid=$1",[req.params.id])
      for (const day of days) await client.query(`INSERT INTO atec.tblworkscheduleday
        (scheduleid,weekday,normal_start,normal_end,unpaid_break_minutes,is_overtime_day)
        VALUES($1,$2,$3,$4,$5,$6)`, [
        req.params.id,day.weekday,day.normal_start || null,day.normal_end || null,
        Number(day.unpaid_break_minutes || 0),day.is_overtime_day === true
      ])
      await client.query("COMMIT")
      res.json(result.rows[0])
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {})
      throw error
    } finally { client.release() }
  }))

  router.get("/hr/dashboard", asyncRoute(async (req, res) => {
    if (!canAdminWorkforce(req.user)) return res.status(403).json({ error:"Access denied" })
    const result = await pool.query(`SELECT
      count(*) FILTER(WHERE status='EMPLOYEE_SUBMITTED')::int AS awaiting_manager,
      count(*) FILTER(WHERE status='MANAGER_APPROVED')::int AS awaiting_hr,
      count(*) FILTER(WHERE status='HR_ACCEPTED')::int AS payroll_ready,
      count(*) FILTER(WHERE status='RETURNED')::int AS returned
      FROM atec.tbldailytimesheet WHERE timesheet_date >= CURRENT_DATE-INTERVAL '31 days'`)
    res.json(result.rows[0])
  }))

  router.get("/timesheets/:id/pdf", pdfLimiter, asyncRoute(async (req, res) => {
    const sheet = await loadTimesheetPdfData(pool, req.params.id)
    if (!sheet) return res.status(404).json({ error:"Timesheet not found" })
    if (Number(sheet.user_id) !== Number(req.user.user_id) && !["ADMIN","MANAGER","HR"].includes(req.user.role)) {
      return res.status(403).json({ error:"Access denied" })
    }
    if (req.user.role === "MANAGER" && Number(sheet.manager_user_id) !== Number(req.user.user_id)) {
      return res.status(403).json({ error:"This timesheet is not assigned to you" })
    }
    const buffer = await createTimesheetPdfBuffer(sheet, { brandRoot })
    const filename = `FBC009-10-${String(sheet.timesheet_date).slice(0,10)}-${sheet.user_id}.pdf`
    res.setHeader("Content-Type", "application/pdf")
    res.setHeader("Content-Disposition", `inline; filename="${filename}"`)
    res.send(buffer)
  }))

  router.get("/job-cards/:id/accelo-readiness", asyncRoute(async (req, res) => {
    if (!["ADMIN","MANAGER","INSPECTOR"].includes(req.user.role)) return res.status(403).json({ error:"Access denied" })
    const readiness = await loadAcceloReadiness(pool, req.params.id)
    if (!readiness) return res.status(404).json({ error:"Job Card not found" })
    res.json(readiness)
  }))

  router.post("/job-cards/:id/accelo-send", emailLimiter, asyncRoute(async (req, res) => {
    if (!["ADMIN","MANAGER"].includes(req.user.role)) return res.status(403).json({ error:"Access denied" })
    const readiness = await loadAcceloReadiness(pool, req.params.id)
    if (!readiness) return res.status(404).json({ error:"Job Card not found" })
    if (!readiness.ready) return res.status(409).json({ error:"The Accelo package is not ready.", issues:readiness.issues })
    if (readiness.card.accelo_email_sent_at && req.body?.resend !== true) {
      return res.status(409).json({ error:"This Accelo package has already been sent. Select resend explicitly if another copy is required." })
    }
    const mailIssues = getMailConfigIssues()
    if (mailIssues.length) return res.status(503).json({ error:`Email is not configured. Missing: ${mailIssues.join(", ")}` })
    const manifest = []
    const attachments = []
    const card = await loadJobCard(req.params.id)
    const cardFilename = `${card.jobcard_reference}.pdf`
    attachments.push({ filename:cardFilename,content:await createJobCardPdfBuffer(card),contentType:"application/pdf" })
    manifest.push({ type:"JOB_CARD",id:card.jobcardid,filename:cardFilename })
    for (const row of readiness.timesheets) {
      const sheet = await loadTimesheetPdfData(pool,row.timesheetid)
      const filename = `FBC009-10-${String(sheet.timesheet_date).slice(0,10)}-${sheet.user_id}.pdf`
      attachments.push({ filename,content:await createTimesheetPdfBuffer(sheet,{brandRoot}),contentType:"application/pdf" })
      manifest.push({ type:"TIMESHEET",id:sheet.timesheetid,filename })
    }
    for (const row of readiness.certificates) {
      const certificate = await getCertificateData(row.testid)
      const filename = `certificate-${row.testid}.pdf`
      attachments.push({ filename,content:await createCertificatePdfBuffer(certificate),contentType:"application/pdf" })
      manifest.push({ type:"CERTIFICATE",id:row.testid,filename })
    }
    const totalBytes = attachments.reduce((sum,item) => sum + item.content.length,0)
    if (totalBytes > 20 * 1024 * 1024) {
      return res.status(413).json({ error:"The Accelo package is larger than 20 MB. Reduce photographs or send the package in controlled parts." })
    }
    const delivery = await pool.query(`INSERT INTO atec.tblaccelodelivery
      (jobcardid,recipient,subject,attachment_manifest,delivery_status,requested_by_user_id)
      VALUES($1,$2,$3,$4,'PENDING',$5) RETURNING deliveryid`, [
      readiness.card.jobcardid,readiness.recipient,
      `ATEC completed job - ${readiness.card.jobcard_reference} - Job ${readiness.card.customer_reference}`,
      JSON.stringify(manifest),req.user.user_id
    ])
    try {
      await sendApplicationEmail({
        from:process.env.MAIL_FROM,
        to:readiness.recipient,
        subject:`ATEC completed job - ${readiness.card.jobcard_reference} - Job ${readiness.card.customer_reference}`,
        text:[
          "Completed ATEC job package.",
          "",
          `Customer: ${readiness.card.clientname}`,
          `Job Card: ${readiness.card.jobcard_reference}`,
          `Accelo Job Number: ${readiness.card.customer_reference}`,
          `Crew timesheets: ${readiness.timesheets.length}`,
          `Certificates: ${readiness.certificates.length}`
        ].join("\n"),
        attachments
      })
      await pool.query(`UPDATE atec.tblaccelodelivery SET delivery_status='SENT',sent_at=now() WHERE deliveryid=$1`, [delivery.rows[0].deliveryid])
      await pool.query(`UPDATE atec.tbljobcard SET accelo_email_to=$1,accelo_email_sent_at=now(),accelo_email_error=NULL
        WHERE jobcardid=$2`, [readiness.recipient,readiness.card.jobcardid])
      res.json({ success:true,recipient:readiness.recipient,attachments:manifest,bytes:totalBytes })
    } catch (error) {
      const message = getMailErrorMessage(error)
      await pool.query(`UPDATE atec.tblaccelodelivery SET delivery_status='FAILED',error_message=$1 WHERE deliveryid=$2`, [message,delivery.rows[0].deliveryid])
      await pool.query(`UPDATE atec.tbljobcard SET accelo_email_to=$1,accelo_email_error=$2 WHERE jobcardid=$3`, [readiness.recipient,message,readiness.card.jobcardid])
      throw error
    }
  }))

  app.use("/workforce", router)
}

module.exports = { registerWorkforceRoutes, rebuildTimesheet, copyJobCardTimeline, loadAcceloReadiness, createPayrollWorkbook }
