const assert = require("assert")
const fs = require("fs")
const path = require("path")

const root = path.join(__dirname, "..", "..")
const read = relative => fs.readFileSync(path.join(root, relative), "utf8")
const migration = read("database/2026-09-04-customer-compliance-documents.sql")
const manifest = JSON.parse(read("deployment/production-migrations.json"))
const contract = JSON.parse(read("deployment/production-schema-contract.json"))
const server = read("backend/server.js")
const main = read("frontend/src/main.js")
const internalPage = read("frontend/src/pages/ComplianceDocuments.js")
const portalPage = read("frontend/src/pages/CustomerPortal.js")

assert(migration.includes("CREATE TABLE IF NOT EXISTS atec.tblcompliancedocument"))
assert(migration.includes("CREATE TABLE IF NOT EXISTS atec.tblcompliancedocumentaudience"))
assert(manifest.migrations.includes("2026-09-04-customer-compliance-documents.sql"))
assert(contract.requirements.some(item => item.table === "tblcompliancedocument"))
assert(server.includes('return ["ADMIN", "MANAGER", "HR"].includes(user?.role)'))
assert(server.includes('complianceDocumentUpload.single("complianceDocument")'))
assert(server.includes('signature !== "%PDF-"'))
assert(server.includes("TO_CHAR(d.expiry_date, 'YYYY-MM-DD') AS expiry_date"))
assert(server.includes('app.get("/customer-portal/compliance-documents"'))
assert(server.includes('app.get("/customer-portal/compliance-documents/:id/download"'))
assert(server.includes("permitted.clientid = $1"))
assert(main.includes("menuButton('compliance-documents','Compliance Documents'"))
assert(internalPage.includes("sortComplianceDocuments"))
assert(internalPage.includes('sortHeading("Valid Until", "expiry_date")'))
assert(main.includes("window.sortComplianceDocuments = sortComplianceDocuments"))
assert(internalPage.includes("Selected customers only"))
assert(internalPage.includes("Publish now"))
assert(portalPage.includes("Company Compliance Documents"))
assert(portalPage.includes("downloadPortalComplianceDocument"))

console.log("Compliance document library regression checks passed.")
