const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { chromium } = require('C:/Users/JacquesJonker/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
;(async () => {
  const browser = await chromium.launch({headless:true})
  try {
    const page = await browser.newPage({viewport:{width:390,height:844},hasTouch:true,colorScheme:'dark'})
    await page.setContent('<body style="background:#202020;color:white"><div class="signature-pad-wrap"><strong>Sign here — inside the white box</strong><canvas id="jcSignatureCanvas" width="900" height="300"></canvas><p id="jcSignatureStatus" role="status"></p></div><div class="job-card-signature-preview"><img class="job-card-signature-image"></div></body>')
    await page.addStyleTag({content:fs.readFileSync(path.resolve(__dirname,'../../frontend/src/style.css'),'utf8')})
    const source = fs.readFileSync(path.resolve(__dirname,'../../frontend/src/main.js'),'utf8')
    await page.addScriptTag({content:source.slice(source.indexOf('function initialiseJobCardSignature()'),source.indexOf('\nfunction collectJobCardPayload'))+'\ninitialiseJobCardSignature()'})
    assert.equal(await page.evaluate(()=>jobCardCanvasHasInk(document.querySelector('canvas'))),false,'White background is not a signature')
    assert.deepEqual(await page.evaluate(()=>Array.from(document.querySelector('canvas').getContext('2d').getImageData(0,0,1,1).data)),[255,255,255,255])
    assert.equal(await page.locator('.job-card-signature-preview').evaluate(node=>getComputedStyle(node).backgroundColor),'rgb(255, 255, 255)')
    const box = await page.locator('canvas').boundingBox()
    await page.mouse.move(box.x+40,box.y+50)
    await page.mouse.down()
    assert.equal(await page.locator('#jcSignatureStatus').innerText(),'Signing…')
    await page.mouse.move(box.x+180,box.y+100,{steps:12})
    await page.mouse.up()
    assert.equal(await page.evaluate(()=>jobCardCanvasHasInk(document.querySelector('canvas'))),true)
    assert.match(await page.locator('#jcSignatureStatus').innerText(),/save the Job Card/)
    await page.evaluate(()=>clearJobCardSignature())
    assert.equal(await page.evaluate(()=>jobCardCanvasHasInk(document.querySelector('canvas'))),false)
    assert.match(await page.locator('#jcSignatureStatus').innerText(),/Signature cleared/)
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
    console.log('Customer signature browser checks passed: dark mode, mobile, ink detection, drawing status and clear.')
  } finally { await browser.close() }
})().catch(error=>{console.error(error);process.exitCode=1})
