const assert = require("assert")
const fs = require("fs")
const path = require("path")

const root = path.resolve(__dirname, "..", "..")
const read = relativePath => fs.readFileSync(path.join(root, relativePath), "utf8")
const assetsPage = read("frontend/src/pages/AssetSetup.js")
const customerPage = read("frontend/src/pages/CustomerSetup.js")
const sitesPage = read("frontend/src/pages/Sites.js")
const sectionsPage = read("frontend/src/pages/Sections.js")
const responsiblePage = read("frontend/src/pages/ResponsiblePersons.js")
const inspectionsPage = read("frontend/src/pages/Inspections.js")
const styles = read("frontend/src/style.css")

assert.ok(assetsPage.includes('class="asset-setup-page"'))
assert.ok(assetsPage.includes('class="asset-table"'))
assert.ok(assetsPage.includes('data-label="Asset ID"'))
assert.ok(assetsPage.includes('data-label="Actions" class="asset-result-actions"'))
assert.ok(styles.includes(".asset-table .asset-result-card td::before"))
assert.ok(styles.includes("content: attr(data-label)"))
assert.ok(styles.includes(".asset-pagination-bar .report-page-controls span"))
assert.ok(styles.includes("overscroll-behavior-inline: contain"))
for (const page of [customerPage, sitesPage, sectionsPage, responsiblePage, inspectionsPage]) {
  assert.ok(page.includes('class="mobile-card-table'), "Operational list must use the shared mobile card table")
  assert.ok(page.includes('class="mobile-card-row"'), "Operational list rows must become mobile cards")
  assert.ok(page.includes('data-label="Actions" class="mobile-card-actions"'), "Mobile actions must be clearly labelled")
}
assert.ok(styles.includes(".mobile-card-table .mobile-card-row td::before"))
assert.ok(styles.includes(".mobile-card-table .mobile-card-actions .action-buttons"))
assert.ok(styles.includes(".report-pagination-bar .report-page-controls > span:last-child"))
assert.ok(styles.includes(".certificate-table-scroll-region"))
assert.ok(styles.includes(".page-actions button,"))
assert.ok(styles.includes("grid-template-columns: auto minmax(0, 1fr) auto"))
assert.ok(styles.includes("grid-column: 1 / -1"))

console.log("Mobile platform layout regression checks passed.")
