const assert = require("assert")
const fs = require("fs")
const path = require("path")

const root = path.join(__dirname, "..", "..")
const serverSource = fs.readFileSync(path.join(root, "backend", "server.js"), "utf8")
const frontendSource = fs.readFileSync(path.join(root, "frontend", "src", "main.js"), "utf8")
const styleSource = fs.readFileSync(path.join(root, "frontend", "src", "style.css"), "utf8")
const handlerSource = fs.readFileSync(path.join(root, "backend", "middleware", "passwordChange.js"), "utf8")

assert(serverSource.includes('app.post("/users/me/password", passwordChangeLimiter'))
assert(serverSource.includes('routePath === "/users/me/password" && method === "POST"'))
assert(handlerSource.includes('bcrypt.compare(currentPassword, existing.password_hash)'))
assert(handlerSource.includes('bcrypt.compare(newPassword, existing.password_hash)'))
assert(handlerSource.includes('validatePassword(newPassword)'))
assert(handlerSource.includes('req.logAudit("PASSWORD_CHANGE", "users", req.user.user_id)'))
assert(frontendSource.includes('window.changeMyPassword = async function ()'))
assert(frontendSource.includes('autocomplete="current-password"'))
assert(frontendSource.includes('autocomplete="new-password"'))
assert(frontendSource.includes('newPassword !== confirmPassword'))
assert(styleSource.includes('.my-profile-password-card'))

console.log("Self-service password change regression checks passed.")
