const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.resolve(__dirname, '../..')
const main = fs.readFileSync(path.join(root, 'frontend/src/main.js'), 'utf8')
const page = fs.readFileSync(path.join(root, 'frontend/src/pages/RiskAssessments.js'), 'utf8')
const server = fs.readFileSync(path.join(root, 'backend/server.js'), 'utf8')

assert(main.includes("menuGroup('risk-assessment','Risk Assesment'"))
assert(main.includes("menuButton('she-reports','Reporting','showRiskAssessmentReports()')"))
assert(main.includes("'she-reports': ['ADMIN', 'MANAGER', 'INSPECTOR', 'VIEWER']"))
assert(page.includes('Print Report'))
assert(page.includes("downloadRiskAssessments('pdf')"))
assert(page.includes('downloadRiskAssessmentPdf(${risk.riskid})'))
assert(page.includes('printRiskAssessment(${risk.riskid})'))
assert(main.includes('window.downloadRiskAssessmentPdf = async function'))
assert(main.includes('window.printRiskAssessment = function'))
assert(main.includes("window.canWriteRiskAssessments = ['ADMIN', 'MANAGER', 'INSPECTOR'].includes(currentUser?.role)"))
assert(main.includes('window.editRiskAssessment = async function'))
assert(!page.slice(page.indexOf('export async function renderRiskAssessments'), page.indexOf('export async function renderRiskAssessmentReports')).includes('id="riskAssessmentTable"'))
assert(server.includes('app.get("/she/risk-assessments/:id.pdf", pdfLimiter'))
assert(server.includes('createSlammPdf(row, res'))
console.log('SLAMM navigation and reporting regression passed')
