const assert = require("assert")
const fs = require("fs")
const path = require("path")

const root = path.resolve(__dirname, "../..")

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8")
}

function assertIncludes(source, needle, message) {
  assert(source.includes(needle), `${message}\nMissing: ${needle}`)
}

const server = read("backend/server.js")
const frontend = read("frontend/src/main.js")
const style = read("frontend/src/style.css")
const migration = read("database/2026-07-15-task14-onsite-inspection-visits.sql")
const docs = read("docs/onsite-inspection-visits.md")
const roadmap = read("docs/next-roadmap-tasks-13-16.md")
const packageJson = JSON.parse(read("package.json"))

assertIncludes(server, "const VISIT_ACTIVE_STATUSES", "Visit active statuses must be defined")
assertIncludes(server, "const VISIT_RESOLVED_STATUSES", "Reconciliation statuses must be defined")
assertIncludes(server, "function canCreateOrCloseVisit", "Admin/Manager closure permission helper is missing")
assertIncludes(server, "function canWorkVisit", "Inspector visit work permission helper is missing")
assertIncludes(server, "function normalizeVisitCreationStatus", "Visit creation must prevent closed-state creation")
assertIncludes(server, "buildVisitWorklistRows", "Due worklist snapshot helper is missing")
assertIncludes(server, "latest_visual", "Latest visual due source must be queried")
assertIncludes(server, "latest_load", "Latest load-test due source must be queried")
assertIncludes(server, "validdate", "Due-date logic must use existing validdate")
assertIncludes(server, "COALESCE(a.archived, false) = false", "Snapshot must exclude archived assets")
assertIncludes(server, "a.clientid = $1", "Snapshot must be customer scoped")
assertIncludes(server, "a.siteid = $2", "Snapshot must be site scoped")
assertIncludes(server, "($3::int IS NULL OR a.sectionid = $3::int)", "Snapshot must support optional section filtering")
assertIncludes(server, "ON CONFLICT (visitid, assetid, required_inspection_scope) DO NOTHING", "Duplicate worklist prevention is missing")

assertIncludes(server, 'app.post("/inspection-visits/preview"', "Visit preview route is missing")
assertIncludes(server, 'app.post("/inspection-visits"', "Visit creation route is missing")
assertIncludes(server, 'app.get("/inspection-visits/active-match"', "QR/NFC active visit match route is missing")
assertIncludes(server, 'app.post("/inspection-visits/:id/scan"', "Visit scan route is missing")
assertIncludes(server, 'app.put("/inspection-visits/:id/assets/:visitassetid/disposition"', "Disposition route is missing")
assertIncludes(server, 'app.post("/inspection-visits/:id/discoveries"', "New asset discovery route is missing")
assertIncludes(server, 'app.post("/inspection-visits/:id/close"', "Closure route is missing")
assertIncludes(server, 'app.get("/inspection-visits/:id/report"', "Visit report route is missing")
assertIncludes(server, 'app.get("/dashboard/visit-alerts"', "Visit dashboard route is missing")

assertIncludes(server, "VISIT_COMMENT_REQUIRED_STATUSES", "Mandatory comments rule is missing")
assertIncludes(server, "Customer confirmation is required.", "Customer-confirmed removal rule is missing")
assertIncludes(server, "Completed requires the required linked inspection or load test.", "Completed disposition must require linked inspections")
assertIncludes(server, "completed_at = CASE WHEN $1 = 'COMPLETED'", "Manual completion must stamp completed_at")
assertIncludes(server, "Due assets still unaccounted for.", "Closure must block unresolved assets")
assertIncludes(server, "Only Admin or Manager users can close or override visit closure.", "Inspector closure override denial is missing")
assertIncludes(server, "VISIT_CLOSURE_OVERRIDE", "Closure override audit event is missing")
assertIncludes(server, "VISIT_ASSET_SCANNED", "Asset scanned audit event is missing")
assertIncludes(server, "VISIT_INSPECTION_LINKED", "Inspection linked audit event is missing")
assertIncludes(server, "VISIT_ASSET_DISPOSITION_SET", "Disposition audit event is missing")
assertIncludes(server, "VISIT_ASSET_DISCOVERED", "Discovery audit event is missing")
assertIncludes(server, "VISIT_CLOSE_BLOCKED", "Blocked closure audit event is missing")

assertIncludes(server, "visitid,", "Inspection save must accept explicit visit ID")
assertIncludes(server, "FOR UPDATE OF va", "Inspection linking must be transactional")
assertIncludes(server, "linked_visual_testid", "Visual inspection linking is missing")
assertIncludes(server, "linked_loadtest_testid", "Load-test linking is missing")
assertIncludes(server, "required_inspection_scope === \"BOTH\"", "Both-required partial completion logic is missing")
assertIncludes(server, "visitAsset.required_inspection_scope === normalizedInspectionType", "Inspection type/scope validation is missing")
assertIncludes(server, "reconciliation_status = CASE WHEN $3::boolean THEN 'COMPLETED'", "Completion update must be conditional")

assertIncludes(frontend, "visits: ['ADMIN', 'MANAGER', 'INSPECTOR']", "Visit page access must exclude Viewer and Customer")
assertIncludes(frontend, "On-Site Visits", "Visit navigation is missing")
assertIncludes(frontend, "showInspectionVisits", "Visit page function is missing")
assertIncludes(frontend, "previewInspectionVisit", "Visit preview UI is missing")
assertIncludes(frontend, "createInspectionVisit", "Visit creation UI is missing")
assertIncludes(frontend, "openInspectionVisit", "Visit worklist UI is missing")
assertIncludes(frontend, "renderVisitAssetCard", "Mobile worklist card renderer is missing")
assertIncludes(frontend, "markVisitAssetScanned", "Scan does not equal completion hook is missing")
assertIncludes(frontend, "setVisitAssetDisposition", "Disposition UI is missing")
assertIncludes(frontend, "addVisitDiscovery", "Discovery UI is missing")
assertIncludes(frontend, "closeInspectionVisit", "Closure UI is missing")
assertIncludes(frontend, "printInspectionVisitReport", "Report UI is missing")
assertIncludes(frontend, "loadActiveVisitMatch", "QR/NFC active visit integration is missing")
assertIncludes(frontend, "Open in Visit", "Single matching visit prompt is missing")
assertIncludes(frontend, "Choose Active Visit", "Multiple matching visit prompt is missing")
assertIncludes(frontend, "formData.append(\"visitid\"", "Visit ID must be carried through inspection save")
assertIncludes(frontend, "visit:", "Inspection return path must support visit origin")
assertIncludes(style, ".visit-count-grid", "Visit counts mobile style is missing")
assertIncludes(style, ".visit-asset-card", "Visit worklist card style is missing")

assertIncludes(migration, "CREATE TABLE IF NOT EXISTS atec.tblinspectionvisit", "Visit table migration is missing")
assertIncludes(migration, "CREATE TABLE IF NOT EXISTS atec.tblinspectionvisitasset", "Visit asset snapshot table is missing")
assertIncludes(migration, "CREATE TABLE IF NOT EXISTS atec.tblinspectionvisitmember", "Visit member table is missing")
assertIncludes(migration, "CREATE TABLE IF NOT EXISTS atec.tblinspectionvisitactivity", "Visit activity table is missing")
assertIncludes(migration, "CREATE TABLE IF NOT EXISTS atec.tblinspectionvisitdiscovery", "Visit discovery table is missing")
assertIncludes(migration, "clientid_snapshot", "Customer snapshot column is missing")
assertIncludes(migration, "siteid_snapshot", "Site snapshot column is missing")
assertIncludes(migration, "sectionid_snapshot", "Section snapshot column is missing")
assertIncludes(migration, "visual_due_date_at_start", "Visual due snapshot is missing")
assertIncludes(migration, "loadtest_due_date_at_start", "Load-test due snapshot is missing")
assertIncludes(migration, "linked_visual_testid", "Linked visual inspection column is missing")
assertIncludes(migration, "linked_loadtest_testid", "Linked load-test column is missing")
assertIncludes(migration, "first_scanned_at", "Scan timestamp column is missing")
assertIncludes(migration, "idx_tblinspectionvisit_client_site_status", "Customer/site/status index is missing")
assertIncludes(migration, "idx_tblinspectionvisitasset_outstanding", "Outstanding reconciliation index is missing")
assertIncludes(migration, "Read-only audit", "Migration audit queries are missing")
assertIncludes(migration, "Rollback guidance", "Migration rollback guidance is missing")

assertIncludes(docs, "Visit Lifecycle", "Visit lifecycle docs are missing")
assertIncludes(docs, "Due-Asset Snapshot", "Due snapshot docs are missing")
assertIncludes(docs, "QR/NFC Linking", "QR/NFC linking docs are missing")
assertIncludes(docs, "Inspection Linking", "Inspection linking docs are missing")
assertIncludes(docs, "Reconciliation Statuses", "Reconciliation status docs are missing")
assertIncludes(docs, "Missing-Unit Handling", "Missing unit docs are missing")
assertIncludes(docs, "New Asset Discovery", "Discovery docs are missing")
assertIncludes(docs, "Closure Rules", "Closure docs are missing")
assertIncludes(docs, "Future Customer Portal Integration", "Task 15 prep docs are missing")
assertIncludes(docs, "Future Email/Notification Events", "Task 16 prep docs are missing")
assertIncludes(roadmap, "Task 13: NFC Asset Support - Complete Locally", "Roadmap must mark Task 13 complete locally")
assertIncludes(roadmap, "Task 14: On-Site Due-Asset Coverage - Complete Locally", "Roadmap must mark Task 14 complete locally")
assertIncludes(roadmap, "Task 15: Customer Portal - Next", "Roadmap must keep Task 15 next")
assertIncludes(roadmap, "Task 16: Email And Notifications - After Task 15", "Roadmap must keep Task 16 after Task 15")

assert.strictEqual(packageJson.scripts["test:task14"], "node scripts/regression/task14-onsite-visit-coverage.test.js")
assert(packageJson.scripts["test:task13"], "Task 13 regression script should remain available")
assert(packageJson.scripts["test:task12-framework"], "Task 12 framework regression should remain available")
assert(packageJson.scripts["test:task11"], "Task 11 regression should remain available")
assert(packageJson.scripts["test:task10"], "Task 10 regression should remain available")
assert(packageJson.scripts["test:task9"], "Task 9 regression should remain available")
assert(packageJson.scripts["test:task7"], "Task 7 regression should remain available")

console.log("Task 14 onsite visit coverage regression checks passed")
