const assert = require("assert")
const fs = require("fs")
const path = require("path")

const root = path.resolve(__dirname, "../..")

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8")
}

function assertIncludes(source, needle, message) {
  assert(source.includes(needle), `${message}\nMissing: ${needle}`)
}

const server = read("backend/server.js")
const main = read("frontend/src/main.js")
const portal = read("frontend/src/pages/CustomerPortal.js")
const style = read("frontend/src/style.css")
const roadmap = read("docs/next-roadmap-tasks-13-16.md")
const packageJson = JSON.parse(read("package.json"))

assertIncludes(server, 'app.get("/customer-portal/summary", requireAuth', "Customer portal summary route must be authenticated")
assertIncludes(server, 'app.get("/customer-portal/assets", requireAuth', "Customer portal asset route must be authenticated")
assertIncludes(server, 'req.user.role !== "CUSTOMER"', "Customer portal summary route must be customer-only")
assertIncludes(server, "const effectiveClientId = req.user.clientid", "Customer portal must derive client scope from logged-in user")
assertIncludes(server, "WHERE clientid = $1", "Customer lookup must be scoped by client ID")
assertIncludes(server, "WHERE a.clientid = $1", "Certificate summary must be scoped by customer asset ownership")
assertIncludes(server, "WHERE v.clientid = $1", "Visit summary must be scoped by customer visit ownership")
assertIncludes(server, "COALESCE(a.archived, false) = false", "Customer portal assets must exclude archived assets")
assertIncludes(server, "asset_status = $", "Customer portal assets must support status filtering")
assertIncludes(server, "recentCertificates", "Portal summary must expose recent certificates")
assertIncludes(server, 'const effectiveUsername = role === "CUSTOMER" ? trimmedEmail : trimmedUsername', "Customer portal usernames must be derived from email on create")
assertIncludes(server, "username = CASE WHEN $4 = 'CUSTOMER' THEN $1 ELSE username END", "Customer portal usernames must follow email on save")
assertIncludes(server, 'role === "CUSTOMER" && !trimmedEmail', "Customer portal users must require an email username")
assertIncludes(server, "sectionid = $8", "Customer portal user saves must persist the section payload position")
assertIncludes(server, "role === \"CUSTOMER\" ? siteid || null : null", "Customer portal users may be tied to customer/site scope")
assertIncludes(server, 'canManageCustomerPortalUsers(user)', "Managers must be allowed to manage customer portal users")
assertIncludes(server, 'Managers can only create customer portal users', "Managers must not be able to create internal ATEC users")
assertIncludes(server, 'Managers can only edit customer portal users', "Managers must not be able to edit internal ATEC users")
assertIncludes(server, 'Managers can only reset customer portal user passwords', "Managers must not be able to reset internal ATEC user passwords")

assertIncludes(main, "portal: ['CUSTOMER']", "Portal page access must be customer-only")
assertIncludes(main, "if (pageKey === 'portal') return currentUser?.role === 'CUSTOMER'", "Admins must not be routed into the customer-only portal")
assertIncludes(main, "renderCustomerPortal", "Customer portal renderer must be imported")
assertIncludes(main, "currentUser.role === 'CUSTOMER' ? 'portal' : 'dashboard'", "Customer login must land on portal")
assertIncludes(main, "menuButton('portal', 'Customer Portal'", "Customer Portal navigation item is missing")
assertIncludes(main, "menuButton('users', 'Customer Portal Users', 'showCustomerUserManagement()')", "Admin navigation must expose customer user management directly")
assertIncludes(main, 'case "portal":', "Portal route restore case is missing")
assertIncludes(main, "const internalUserRoles = ['ADMIN', 'MANAGER', 'INSPECTOR', 'VIEWER']", "Internal ATEC user roles must be managed separately")
assertIncludes(main, "const customerUserRoles = ['CUSTOMER']", "Customer portal user roles must be managed separately")
assertIncludes(main, "userBelongsToManagementMode", "User management must filter internal and customer users separately")
assertIncludes(main, "showCustomerUserManagement", "Customer portal user management view is missing")
assertIncludes(main, "Please link this customer portal user to a customer.", "Customer portal users must require a linked customer")
assertIncludes(main, "syncCustomerUsernameWithEmail", "Customer portal username must sync from email in the admin form")
assertIncludes(main, "Customer login username is always the email address.", "Customer portal user management must explain email-as-username")
assertIncludes(main, "Customer portal users are linked to the customer and site, not to one section.", "Customer portal user management must explain section scope")
assertIncludes(main, "customer-users-table", "Customer portal user list must have its own table mode")
assertIncludes(main, "sectionid: null", "Customer portal user saves must clear section scope")
assertIncludes(main, "users: ['ADMIN', 'MANAGER']", "Managers must be able to open customer portal user management")
assertIncludes(main, "function canManageInternalUsers()", "Internal ATEC user management must remain admin-only in the UI")
assertIncludes(main, "if (!canManageInternalUsers()) return 'customers'", "Managers must land on Customer Portal Users")

assertIncludes(portal, "/customer-portal/summary", "Portal page must call the scoped summary endpoint")
assertIncludes(portal, "/customer-portal/assets", "Portal page must call the scoped asset endpoint")
assertIncludes(portal, "showCertificateSearch()", "Portal must link to certificates")
assertIncludes(portal, "showCustomerDetailedReport({ autoLoad: true })", "Portal must link to auto-loaded detailed reports")
assertIncludes(portal, "Recent Certificates", "Portal must show recent certificates")
assertIncludes(portal, "Visit Outstanding", "Portal must show visit context")
assertIncludes(portal, "portalAssetSearch", "Portal asset search control is missing")
assertIncludes(portal, "portalAssetStatus", "Portal asset status filter is missing")
assertIncludes(portal, "visual_testid", "Portal assets must link visual certificates")
assertIncludes(portal, "loadtest_testid", "Portal assets must link load-test certificates")

assertIncludes(style, ".customer-portal-page", "Portal page styles are missing")
assertIncludes(style, ".portal-metric-grid", "Portal metric grid styles are missing")
assertIncludes(style, ".portal-certificate-table", "Portal certificate table styles are missing")
assertIncludes(style, ".portal-asset-filters", "Portal asset filter styles are missing")
assertIncludes(style, ".portal-asset-table", "Portal asset table styles are missing")
assertIncludes(style, ".user-management-mode-tabs", "User management mode tab styles are missing")

assertIncludes(roadmap, "Task 15: Customer Portal - Complete Locally", "Roadmap must mark Task 15 complete locally")
assert.strictEqual(packageJson.scripts["test:task15"], "node scripts/regression/task15-customer-portal.test.js")

console.log("Task 15 customer portal regression checks passed")
