const assert = require("assert")
const fs = require("fs")
const path = require("path")

const root = path.resolve(__dirname, "..", "..")
const server = fs.readFileSync(path.join(root, "backend", "server.js"), "utf8")
const frontend = fs.readFileSync(path.join(root, "frontend", "src", "main.js"), "utf8")
const migration = fs.readFileSync(path.join(root, "database", "2026-07-21-technician-job-cards.sql"), "utf8")
const workforceRoutes = fs.readFileSync(path.join(root, "backend", "routes", "workforce.js"), "utf8")
const productionMigrations = fs.readFileSync(path.join(root, "deployment", "production-migrations.json"), "utf8")
const automaticHoursMigration = fs.readFileSync(path.join(root, "database", "2026-08-18-job-card-automatic-time-categories.sql"), "utf8")

for (const table of ["tbljobcard", "tbljobcardasset", "tbljobcardmaterial", "tbljobcarddeviation", "tbljobcardphoto"]) {
  assert.match(migration, new RegExp(`CREATE TABLE IF NOT EXISTS atec\\.${table}`))
}

for (const route of [
  'app.get("/job-cards"',
  'app.get("/job-cards/:id"',
  'app.post("/job-cards"',
  'app.put("/job-cards/:id"',
  'app.post("/job-cards/:id/photos"',
  'app.get("/job-cards/:id/pdf"'
]) assert.ok(server.includes(route), `Missing route: ${route}`)

assert.ok(server.includes("A critical deviation requires Out of Service or Restricted status"))
assert.ok(server.includes("Capture the customer signature or provide an unavailable/refused reason"))
assert.ok(server.includes("Select at least one asset for the job card"),"The API must reject job cards without a selected asset")
assert.ok(server.includes("Only an Admin or Manager can approve, invoice or cancel a job card"))
assert.ok(server.includes("await copyJobCardTimeline(client, jobcardid, req.user.user_id)"),"Job-card submission must copy crew time inside the server transaction")
assert.ok(!frontend.includes("/copy-timeline"),"The browser must not perform a second-phase crew-time copy")
assert.ok(frontend.includes("const crewLocked = ['SUBMITTED', 'APPROVED', 'INVOICED', 'CANCELLED']"),"Crew selection must lock after submission")
assert.ok(frontend.includes("adding someone after submission does not automatically backfill their time"),"The UI must explain the post-submission crew-time limitation")
assert.ok(frontend.includes("crewLocked ? 'disabled' : ''"),"Submitted crew checkboxes must be disabled")
assert.ok(workforceRoutes.includes("assertJobCardAccess"),"Crew and timeline routes must use consistent job-card authorization")
assert.ok(frontend.includes("Technician Job Cards"))
assert.ok(frontend.includes("if (!payload.assetids.length)"),"The form must block saving without a selected asset")
assert.ok(frontend.includes("job-card-list-pdf"))
assert.ok(frontend.includes("Open PDF for"))
assert.ok(frontend.includes("Search job cards"),"The job-card queue must support fast searching")
assert.ok(frontend.includes("Awaiting review"),"The job-card queue must separate submitted work for review")
assert.ok(frontend.includes("JOB_CARD_LIST_PAGE_SIZE"),"The job-card queue must paginate high-volume lists")
assert.ok(frontend.includes("jobCardTechnicianFilter"),"Managers must be able to filter the queue by inspector")
assert.ok(frontend.includes("customer_signature_data"))
assert.ok(frontend.includes('id="jobCardCustomerSignature"'),"All job-card roles must have a directly addressable customer-signature section")
assert.ok(frontend.includes("goToCustomerSignature"),"The workflow must take users directly to the customer-signature block")
assert.ok(frontend.includes("Capture Customer Signature"),"Admins and Inspectors must receive an explicit signature-capture action")
assert.ok(frontend.includes("This section is available to Admins and Inspectors"),"The signature section must explain its role availability")
assert.ok(frontend.includes("Accelo Completion Package <small>(Admin/Manager only)</small>"),"The office-only Accelo control must be clearly labelled")
assert.ok(frontend.includes("refreshJobCardHours"),"Job-card hour categories must recalculate from the timestamp fields")
assert.ok(frontend.includes("Double time"),"The job card must show double time")
assert.ok(frontend.includes("Travelling time"),"The job card must show travelling time separately")
assert.ok(frontend.includes("readonly value"),"Automatically calculated job-card hours must not be manually edited")
assert.ok(server.includes('app.post("/job-cards/calculate-hours"'),"The server must provide schedule-aware job-card hour calculations")
assert.ok(server.includes("calculatedHours.normal_hours"),"Saved normal hours must come from the authoritative server calculation")
assert.ok(server.includes("calculatedHours.double_time_hours"),"Saved double-time hours must come from the authoritative server calculation")
assert.ok(server.includes("calculatedHours.travel_hours"),"Saved travel hours must come from the authoritative server calculation")
assert.ok(productionMigrations.includes("2026-08-18-job-card-automatic-time-categories.sql"),"Production must include the new job-card hour columns")
assert.ok(automaticHoursMigration.includes("'2026-08-10', 'National Women''s Day observed'"),"The official observed 2026 public holiday must be seeded for double-time calculations")
assert.ok(server.includes("u.usersignature AS technician_signature_image"))
assert.ok(server.includes("inspectedAssetIdsForJob"))
assert.ok(server.includes("COALESCE(i.record_status, 'ACTIVE') = 'ACTIVE'"))
assert.ok(!server.includes("i.entered_in_error"))
assert.ok(server.includes("eg.groupname AS equipmentgroup"))
assert.ok(server.includes('String(body.job_type || "").toUpperCase() !== "INSPECTIONS"'))
assert.ok(frontend.includes("matching inspected assets are also added automatically when saved"))
assert.ok(frontend.includes("setFilteredJobCardAssets"))
assert.ok(frontend.includes("All equipment groups"))
assert.ok(frontend.includes("All equipment types"))
assert.ok(frontend.includes("jobCardAssetGroupChanged"))
assert.ok(frontend.includes("Select filtered"))
assert.ok(frontend.includes("jobCardCanvasHasInk"))
assert.ok(frontend.includes("Take photo or choose from gallery"),"Mobile users must be offered both camera and gallery selection")
assert.ok(!frontend.includes('id="jcPhotos" type="file" accept="image/jpeg,image/png,image/webp" capture='),"The job-card photo picker must not force camera capture")
assert.ok(frontend.includes("Save for Later"))
assert.ok(frontend.includes("Save & Assign"))
assert.ok(frontend.includes("Save & Submit On-site"))
assert.ok(frontend.includes("Selected photos will upload automatically when the on-site job is submitted"))
assert.ok(frontend.includes("uploadJobCardPhotoFiles"))
assert.ok(frontend.includes("Submit to Office"))
assert.ok(frontend.includes("Email technician when assigned"))
assert.ok(frontend.includes("email_notification"))
assert.ok(frontend.includes("<label>Accelo Job Number *<input id=\"jcReference\""))
assert.ok(frontend.includes('name="jcCrew"'))
assert.ok(frontend.includes("remainingPages"))
assert.ok(frontend.includes("fetch(assetPageUrl(index + 2))"))
assert.ok(server.includes("emailAssignedTechnician"))
assert.ok(server.includes("JOB_CARD_ASSIGNMENT_EMAIL_SENT"))
assert.ok(server.includes("emailSubmittedJobCardToManager"),"Submission must automatically email the assigned technician's Manager")
assert.ok(server.includes("JOB_CARD_SUBMISSION_EMAIL_SENT"),"Successful Manager delivery must be audited")
assert.ok(server.includes("JOB_CARD_SUBMISSION_EMAIL_FAILED"),"Failed Manager delivery must be audited")
assert.ok(server.includes("The assigned technician must have a Manager assigned before the job card can be submitted"),"Submission must require an assigned Manager")
assert.ok(server.includes('req.user.role === "ADMIN" && leadUserId === Number(req.user.user_id)'),"An Admin assigned to their own job card must use the controlled self-approval path")
assert.ok(server.includes('JOB_CARD_SELF_APPROVAL_REQUESTED'),"Admin self-approval requests must be audited")
assert.ok(frontend.includes("['ADMIN', 'INSPECTOR'].includes(currentUser.role) ? currentUser.user_id : ''"),"New Admin job cards must default to the signed-in Admin")
assert.ok(frontend.includes("Submit for My Approval"),"The Admin self-approval action must be clear in the UI")
assert.ok(frontend.includes("No separate Manager approval is required"),"The Admin self-approval exception must be explained")
assert.ok(server.includes('filename: `${card.jobcard_reference}.pdf`'),"The Manager email must attach the completed job-card PDF")
assert.ok(frontend.includes("manager_email_notification"),"The submitter must see the Manager email result")
assert.ok(migration.includes("assignment_email_sent_at"))
assert.ok(server.includes("allowedTransitions"))
assert.ok(server.includes("drawJobCardPdfFrame"))
assert.ok(server.includes("addJobCardPdfPageFrames"))
assert.ok(server.includes("drawJobCardPdfSummary"))
assert.ok(server.includes("drawJobCardPdfPhotoPages"))
assert.ok(server.includes('heading("Job timeline")'),"The PDF must show recorded job dates and times")
assert.ok(server.includes('table("Selected equipment"'),"The PDF must identify the selected assets")
assert.ok(server.includes("candidates.filter(column => rows.some"),"The PDF must omit empty optional table columns")
assert.ok(server.includes("const photosPerPage = columns * rows"))
assert.ok(server.includes('["Job Number", card.customer_reference]'))
assert.ok(server.includes("Page ${index + 1} of ${range.count}"))
assert.ok(frontend.includes("'LOAD_TEST','SERVICES','INSPECTIONS'"))
assert.ok(migration.includes("job_type = 'LOAD_TEST' WHERE job_type = 'MAINTENANCE'"))

console.log("Technician job-card regression checks passed")
