BEGIN;

CREATE TABLE IF NOT EXISTS atec.tblndtreportsequence (
  report_year integer PRIMARY KEY,
  last_number integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtreportsequence_year
    CHECK (report_year BETWEEN 2000 AND 9999),
  CONSTRAINT chk_tblndtreportsequence_number
    CHECK (last_number >= 0)
);

CREATE OR REPLACE FUNCTION atec.next_mpi_report_number(report_date date DEFAULT CURRENT_DATE)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  selected_year integer := EXTRACT(YEAR FROM COALESCE(report_date, CURRENT_DATE))::integer;
  selected_number integer;
BEGIN
  INSERT INTO atec.tblndtreportsequence (report_year, last_number)
  VALUES (selected_year, 1)
  ON CONFLICT (report_year)
  DO UPDATE SET
    last_number = atec.tblndtreportsequence.last_number + 1,
    updated_at = now()
  RETURNING last_number INTO selected_number;

  RETURN 'MPI-' || selected_year::text || '-' || LPAD(selected_number::text, 6, '0');
END;
$$;

CREATE TABLE IF NOT EXISTS atec.tbluserndtqualification (
  qualificationid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid integer NOT NULL REFERENCES atec.tblusers(userid) ON DELETE CASCADE,
  qualification_scheme text NOT NULL,
  ndt_method text NOT NULL DEFAULT 'MT',
  qualification_level integer NOT NULL,
  certificate_number text NOT NULL,
  qualified_on date,
  expires_on date,
  evidence_path text,
  status text NOT NULL DEFAULT 'ACTIVE',
  notes text NOT NULL DEFAULT '',
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tbluserndtqualification_method
    CHECK (ndt_method IN ('MT')),
  CONSTRAINT chk_tbluserndtqualification_level
    CHECK (qualification_level IN (1, 2, 3)),
  CONSTRAINT chk_tbluserndtqualification_status
    CHECK (status IN ('ACTIVE', 'SUSPENDED', 'EXPIRED', 'REVOKED')),
  CONSTRAINT chk_tbluserndtqualification_dates
    CHECK (expires_on IS NULL OR qualified_on IS NULL OR expires_on >= qualified_on)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbluserndtqualification_active_certificate
  ON atec.tbluserndtqualification(userid, ndt_method, certificate_number)
  WHERE status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS idx_tbluserndtqualification_method_level
  ON atec.tbluserndtqualification(ndt_method, qualification_level, status, expires_on);

CREATE TABLE IF NOT EXISTS atec.tblndttestequipment (
  equipmentid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_type text NOT NULL,
  manufacturer text NOT NULL DEFAULT '',
  model text NOT NULL DEFAULT '',
  serial_number text NOT NULL,
  asset_reference text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'ACTIVE',
  notes text NOT NULL DEFAULT '',
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndttestequipment_status
    CHECK (status IN ('ACTIVE', 'OUT_OF_SERVICE', 'RETIRED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tblndttestequipment_active_serial
  ON atec.tblndttestequipment(UPPER(TRIM(serial_number)))
  WHERE status <> 'RETIRED';

CREATE TABLE IF NOT EXISTS atec.tblndtequipmentcalibration (
  calibrationid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipmentid integer NOT NULL REFERENCES atec.tblndttestequipment(equipmentid) ON DELETE CASCADE,
  calibration_type text NOT NULL DEFAULT 'CALIBRATION',
  certificate_number text NOT NULL,
  calibrated_on date NOT NULL,
  due_on date,
  provider text NOT NULL DEFAULT '',
  evidence_path text,
  result text NOT NULL DEFAULT 'PASS',
  notes text NOT NULL DEFAULT '',
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtequipmentcalibration_type
    CHECK (calibration_type IN ('CALIBRATION', 'VERIFICATION', 'INITIAL_VERIFICATION')),
  CONSTRAINT chk_tblndtequipmentcalibration_result
    CHECK (result IN ('PASS', 'FAIL')),
  CONSTRAINT chk_tblndtequipmentcalibration_dates
    CHECK (due_on IS NULL OR due_on >= calibrated_on)
);

CREATE INDEX IF NOT EXISTS idx_tblndtequipmentcalibration_equipment_due
  ON atec.tblndtequipmentcalibration(equipmentid, due_on DESC);

CREATE TABLE IF NOT EXISTS atec.tblndtreport (
  ndtreportid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_number text NOT NULL,
  template_number text NOT NULL DEFAULT 'FBC286',
  template_revision integer NOT NULL DEFAULT 1,
  report_revision integer NOT NULL DEFAULT 0,
  ndt_method text NOT NULL DEFAULT 'MPI',
  report_purpose text NOT NULL DEFAULT 'PRACTICAL_EXAM',
  status text NOT NULL DEFAULT 'DRAFT',
  subject_type text NOT NULL,
  clientid integer NOT NULL REFERENCES atec.tblclients(clientid) ON DELETE RESTRICT,
  siteid integer REFERENCES atec.tblsites(siteid) ON DELETE SET NULL,
  sectionid integer REFERENCES atec.tblsection(sectionid) ON DELETE SET NULL,
  assetid integer REFERENCES atec.tblasset(assetid) ON DELETE SET NULL,
  client_name_snapshot text NOT NULL,
  address_snapshot text NOT NULL DEFAULT '',
  site_name_snapshot text NOT NULL DEFAULT '',
  section_name_snapshot text NOT NULL DEFAULT '',
  item_description text NOT NULL,
  item_size text NOT NULL DEFAULT '',
  serial_number text NOT NULL DEFAULT '',
  material_specification text NOT NULL DEFAULT '',
  customer_reference text NOT NULL DEFAULT '',
  drawing_weld_reference text NOT NULL DEFAULT '',
  test_date date NOT NULL,
  procedure_used text NOT NULL,
  acceptance_standard text NOT NULL,
  area_tested text NOT NULL,
  surface_condition text NOT NULL,
  examination_scope text NOT NULL DEFAULT '',
  primary_outcome text,
  indication_summary text,
  limitations text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  performing_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  performing_qualification_id integer REFERENCES atec.tbluserndtqualification(qualificationid) ON DELETE SET NULL,
  performing_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  level2_certification_required boolean NOT NULL DEFAULT false,
  certifying_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  certifying_qualification_id integer REFERENCES atec.tbluserndtqualification(qualificationid) ON DELETE SET NULL,
  certifying_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  technician_signed_at timestamptz,
  certified_at timestamptz,
  issued_at timestamptz,
  superseded_at timestamptz,
  supersedes_report_id integer REFERENCES atec.tblndtreport(ndtreportid) ON DELETE SET NULL,
  voided_at timestamptz,
  void_reason text NOT NULL DEFAULT '',
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  updated_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtreport_method
    CHECK (ndt_method IN ('MPI')),
  CONSTRAINT chk_tblndtreport_purpose
    CHECK (report_purpose IN ('PRACTICAL_EXAM')),
  CONSTRAINT chk_tblndtreport_status
    CHECK (status IN (
      'DRAFT',
      'READY_FOR_SIGNING',
      'AWAITING_LEVEL_2',
      'RETURNED_FOR_CORRECTION',
      'CERTIFIED',
      'ISSUED',
      'SUPERSEDED',
      'VOID'
    )),
  CONSTRAINT chk_tblndtreport_subject_type
    CHECK (subject_type IN ('ASSET', 'EXTERNAL')),
  CONSTRAINT chk_tblndtreport_subject
    CHECK (
      (subject_type = 'ASSET' AND assetid IS NOT NULL)
      OR (subject_type = 'EXTERNAL' AND item_description <> '')
    ),
  CONSTRAINT chk_tblndtreport_outcome
    CHECK (primary_outcome IS NULL OR primary_outcome IN ('ACCEPTABLE', 'REJECTED', 'INCONCLUSIVE')),
  CONSTRAINT chk_tblndtreport_indication_summary
    CHECK (
      indication_summary IS NULL
      OR indication_summary IN (
        'NO_RELEVANT_INDICATIONS',
        'RELEVANT_INDICATIONS_ACCEPTABLE',
        'RELEVANT_INDICATIONS_REJECTABLE',
        'EXAMINATION_LIMITED'
      )
    ),
  CONSTRAINT chk_tblndtreport_revision
    CHECK (report_revision >= 0),
  CONSTRAINT chk_tblndtreport_certification
    CHECK (
      status NOT IN ('CERTIFIED', 'ISSUED', 'SUPERSEDED')
      OR (
        technician_signed_at IS NOT NULL
        AND certified_at IS NOT NULL
        AND performing_qualification_id IS NOT NULL
        AND (
          level2_certification_required = false
          OR certifying_qualification_id IS NOT NULL
        )
      )
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tblndtreport_number_revision
  ON atec.tblndtreport(report_number, report_revision);

CREATE INDEX IF NOT EXISTS idx_tblndtreport_client_status_date
  ON atec.tblndtreport(clientid, status, test_date DESC);

CREATE INDEX IF NOT EXISTS idx_tblndtreport_asset_date
  ON atec.tblndtreport(assetid, test_date DESC)
  WHERE assetid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tblndtreport_performer_status
  ON atec.tblndtreport(performing_user_id, status);

CREATE TABLE IF NOT EXISTS atec.tblndtmpdetail (
  ndtreportid integer PRIMARY KEY REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  current_type text NOT NULL,
  particle_medium text NOT NULL,
  viewing_method text NOT NULL,
  magnetising_method text NOT NULL DEFAULT 'CONTINUOUS',
  precleaning_method text NOT NULL DEFAULT '',
  white_background_application text NOT NULL DEFAULT '',
  post_cleaning_required boolean NOT NULL DEFAULT false,
  post_cleaning_method text NOT NULL DEFAULT '',
  surface_temperature_c numeric(8,2),
  visible_light_lux numeric(12,2),
  uva_intensity_uw_cm2 numeric(12,2),
  demagnetisation_gauss numeric(10,3),
  flux_indicator_type text NOT NULL DEFAULT 'NOT_APPLICABLE',
  flux_indicator_result text NOT NULL DEFAULT '',
  technique_notes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtmpdetail_current_type
    CHECK (current_type IN ('AC', 'DC')),
  CONSTRAINT chk_tblndtmpdetail_particle_medium
    CHECK (particle_medium IN ('WET_INK', 'DRY_POWDER')),
  CONSTRAINT chk_tblndtmpdetail_viewing_method
    CHECK (viewing_method IN ('VISIBLE_CONTRAST', 'FLUORESCENT')),
  CONSTRAINT chk_tblndtmpdetail_magnetising_method
    CHECK (magnetising_method IN ('CONTINUOUS')),
  CONSTRAINT chk_tblndtmpdetail_background
    CHECK (white_background_application IN ('', 'AEROSOL', 'BULK_PAINTED', 'NOT_USED', 'OTHER')),
  CONSTRAINT chk_tblndtmpdetail_flux_indicator
    CHECK (flux_indicator_type IN ('A', 'G', 'NOT_APPLICABLE'))
);

CREATE TABLE IF NOT EXISTS atec.tblndtreportequipment (
  reportequipmentid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ndtreportid integer NOT NULL REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  equipmentid integer REFERENCES atec.tblndttestequipment(equipmentid) ON DELETE SET NULL,
  equipment_type text NOT NULL,
  manufacturer_snapshot text NOT NULL DEFAULT '',
  model_snapshot text NOT NULL DEFAULT '',
  serial_number_snapshot text NOT NULL DEFAULT '',
  calibration_type_snapshot text NOT NULL DEFAULT '',
  calibrated_on_snapshot date,
  calibration_due_snapshot date,
  certificate_number_snapshot text NOT NULL DEFAULT '',
  reading_value numeric(14,4),
  reading_unit text NOT NULL DEFAULT '',
  verification_result text NOT NULL DEFAULT '',
  compliant_at_test boolean NOT NULL,
  notes text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tblndtreportequipment_report
  ON atec.tblndtreportequipment(ndtreportid, sort_order, reportequipmentid);

CREATE TABLE IF NOT EXISTS atec.tblndtreportconsumable (
  reportconsumableid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ndtreportid integer NOT NULL REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  consumable_type text NOT NULL,
  manufacturer text NOT NULL DEFAULT '',
  product_code text NOT NULL DEFAULT '',
  batch_number text NOT NULL DEFAULT '',
  expires_on date,
  compliant_at_test boolean NOT NULL,
  notes text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtreportconsumable_type
    CHECK (consumable_type IN ('CLEANER_REMOVER', 'MAGNETIC_INK', 'WHITE_BACKGROUND', 'OTHER'))
);

CREATE INDEX IF NOT EXISTS idx_tblndtreportconsumable_report
  ON atec.tblndtreportconsumable(ndtreportid, sort_order, reportconsumableid);

CREATE TABLE IF NOT EXISTS atec.tblndtreportcheck (
  reportcheckid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ndtreportid integer NOT NULL REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  check_code text NOT NULL,
  check_label_snapshot text NOT NULL,
  limit_snapshot text NOT NULL,
  result text NOT NULL,
  result_note text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtreportcheck_result
    CHECK (result IN ('YES', 'NO', 'NOT_APPLICABLE')),
  UNIQUE (ndtreportid, check_code)
);

CREATE INDEX IF NOT EXISTS idx_tblndtreportcheck_report
  ON atec.tblndtreportcheck(ndtreportid, sort_order, reportcheckid);

CREATE TABLE IF NOT EXISTS atec.tblndtindication (
  indicationid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ndtreportid integer NOT NULL REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  sequence_number integer NOT NULL,
  examined_area text NOT NULL DEFAULT '',
  datum_description text NOT NULL DEFAULT '',
  distance_from_datum_mm numeric(12,3),
  datum_direction text NOT NULL DEFAULT '',
  distance_from_centreline_mm numeric(12,3),
  centreline_side text NOT NULL DEFAULT '',
  length_mm numeric(12,3),
  width_mm numeric(12,3),
  suggested_classification text,
  confirmed_classification text NOT NULL,
  relevance text NOT NULL,
  code_disposition text NOT NULL,
  description text NOT NULL DEFAULT '',
  diagram_number integer,
  diagram_x numeric(7,6),
  diagram_y numeric(7,6),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtindication_sequence
    CHECK (sequence_number > 0),
  CONSTRAINT chk_tblndtindication_dimensions
    CHECK (
      (distance_from_datum_mm IS NULL OR distance_from_datum_mm >= 0)
      AND (distance_from_centreline_mm IS NULL OR distance_from_centreline_mm >= 0)
      AND (length_mm IS NULL OR length_mm >= 0)
      AND (width_mm IS NULL OR width_mm >= 0)
    ),
  CONSTRAINT chk_tblndtindication_suggested_classification
    CHECK (
      suggested_classification IS NULL
      OR suggested_classification IN ('LINEAR', 'ROUNDED', 'GROUPED')
    ),
  CONSTRAINT chk_tblndtindication_confirmed_classification
    CHECK (confirmed_classification IN ('LINEAR', 'ROUNDED', 'GROUPED')),
  CONSTRAINT chk_tblndtindication_relevance
    CHECK (relevance IN ('RELEVANT', 'NON_RELEVANT')),
  CONSTRAINT chk_tblndtindication_disposition
    CHECK (code_disposition IN ('ACCEPTABLE', 'REJECTABLE', 'UNDETERMINED')),
  CONSTRAINT chk_tblndtindication_diagram
    CHECK (
      (diagram_number IS NULL AND diagram_x IS NULL AND diagram_y IS NULL)
      OR (
        diagram_number IS NOT NULL
        AND diagram_number > 0
        AND diagram_x BETWEEN 0 AND 1
        AND diagram_y BETWEEN 0 AND 1
      )
    ),
  UNIQUE (ndtreportid, sequence_number)
);

CREATE INDEX IF NOT EXISTS idx_tblndtindication_report
  ON atec.tblndtindication(ndtreportid, sequence_number);

CREATE TABLE IF NOT EXISTS atec.tblndtreportattachment (
  attachmentid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ndtreportid integer NOT NULL REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  indicationid integer REFERENCES atec.tblndtindication(indicationid) ON DELETE CASCADE,
  attachment_type text NOT NULL DEFAULT 'GENERAL',
  file_path text NOT NULL,
  original_filename text NOT NULL DEFAULT '',
  caption text NOT NULL DEFAULT '',
  uploaded_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtreportattachment_type
    CHECK (attachment_type IN (
      'GENERAL',
      'COMPONENT_OVERVIEW',
      'SURFACE_PREPARATION',
      'INDICATION',
      'DIAGRAM',
      'CALIBRATION_EVIDENCE',
      'QUALIFICATION_EVIDENCE'
    ))
);

CREATE INDEX IF NOT EXISTS idx_tblndtreportattachment_report
  ON atec.tblndtreportattachment(ndtreportid, indicationid, attachmentid);

CREATE TABLE IF NOT EXISTS atec.tblndtsignatureevent (
  signatureeventid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ndtreportid integer NOT NULL REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  report_revision integer NOT NULL,
  signature_role text NOT NULL,
  userid integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  qualificationid integer REFERENCES atec.tbluserndtqualification(qualificationid) ON DELETE SET NULL,
  signer_snapshot jsonb NOT NULL,
  record_hash text NOT NULL,
  decision text NOT NULL,
  comments text NOT NULL DEFAULT '',
  signed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtsignatureevent_revision
    CHECK (report_revision >= 0),
  CONSTRAINT chk_tblndtsignatureevent_role
    CHECK (signature_role IN ('PERFORMING_TECHNICIAN', 'LEVEL_2_CERTIFIER')),
  CONSTRAINT chk_tblndtsignatureevent_decision
    CHECK (decision IN ('SIGNED', 'CERTIFIED', 'RETURNED'))
);

CREATE INDEX IF NOT EXISTS idx_tblndtsignatureevent_report
  ON atec.tblndtsignatureevent(ndtreportid, report_revision, signed_at);

CREATE TABLE IF NOT EXISTS atec.tblndtreportrevision (
  reportrevisionid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ndtreportid integer NOT NULL REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  report_revision integer NOT NULL,
  revision_snapshot jsonb NOT NULL,
  record_hash text NOT NULL,
  revision_reason text NOT NULL DEFAULT '',
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ndtreportid, report_revision)
);

CREATE TABLE IF NOT EXISTS atec.tblndtauditevent (
  auditeventid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ndtreportid integer REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  actor_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  event_type text NOT NULL,
  from_status text,
  to_status text,
  event_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tblndtauditevent_report
  ON atec.tblndtauditevent(ndtreportid, created_at, auditeventid);

CREATE TABLE IF NOT EXISTS atec.tblndtreportdelivery (
  reportdeliveryid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ndtreportid integer NOT NULL REFERENCES atec.tblndtreport(ndtreportid) ON DELETE CASCADE,
  report_revision integer NOT NULL,
  delivery_method text NOT NULL DEFAULT 'EMAIL',
  recipient_email text NOT NULL,
  email_subject text NOT NULL,
  email_message text NOT NULL DEFAULT '',
  delivery_status text NOT NULL,
  error_message text NOT NULL DEFAULT '',
  sent_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblndtreportdelivery_revision
    CHECK (report_revision >= 0),
  CONSTRAINT chk_tblndtreportdelivery_method
    CHECK (delivery_method IN ('EMAIL')),
  CONSTRAINT chk_tblndtreportdelivery_status
    CHECK (delivery_status IN ('SENT', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_tblndtreportdelivery_report
  ON atec.tblndtreportdelivery(ndtreportid, created_at DESC, reportdeliveryid DESC);

COMMIT;
