BEGIN;

CREATE TABLE IF NOT EXISTS atec.tbljobcard (
  jobcardid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobcard_reference text NOT NULL UNIQUE,
  clientid integer NOT NULL REFERENCES atec.tblclients(clientid) ON DELETE RESTRICT,
  siteid integer NOT NULL REFERENCES atec.tblsites(siteid) ON DELETE RESTRICT,
  sectionid integer REFERENCES atec.tblsection(sectionid) ON DELETE SET NULL,
  visitid integer REFERENCES atec.tblinspectionvisit(visitid) ON DELETE SET NULL,
  assigned_to_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  approved_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  job_type text NOT NULL DEFAULT 'REPAIR',
  priority text NOT NULL DEFAULT 'NORMAL',
  status text NOT NULL DEFAULT 'DRAFT',
  customer_reference text NOT NULL DEFAULT '',
  customer_contact_name text NOT NULL DEFAULT '',
  customer_contact_phone text NOT NULL DEFAULT '',
  reported_fault text NOT NULL DEFAULT '',
  findings text NOT NULL DEFAULT '',
  root_cause text NOT NULL DEFAULT '',
  work_performed text NOT NULL DEFAULT '',
  test_performed text NOT NULL DEFAULT '',
  test_result text NOT NULL DEFAULT '',
  recommendations text NOT NULL DEFAULT '',
  equipment_status text NOT NULL DEFAULT 'NOT_TESTED',
  equipment_status_reason text NOT NULL DEFAULT '',
  planned_at timestamptz,
  departed_at timestamptz,
  arrived_at timestamptz,
  work_started_at timestamptz,
  work_completed_at timestamptz,
  travel_completed_at timestamptz,
  kilometres numeric(10,2),
  normal_hours numeric(8,2),
  overtime_hours numeric(8,2),
  standby_hours numeric(8,2),
  customer_signatory_name text NOT NULL DEFAULT '',
  customer_signatory_designation text NOT NULL DEFAULT '',
  customer_signature_path text,
  customer_signed_at timestamptz,
  signature_unavailable_reason text NOT NULL DEFAULT '',
  submitted_at timestamptz,
  approved_at timestamptz,
  invoice_reference text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tbljobcard_type CHECK (job_type IN ('BREAKDOWN','REPAIR','MAINTENANCE','INSTALLATION','INVESTIGATION','OTHER')),
  CONSTRAINT chk_tbljobcard_priority CHECK (priority IN ('LOW','NORMAL','HIGH','URGENT')),
  CONSTRAINT chk_tbljobcard_status CHECK (status IN ('DRAFT','ASSIGNED','IN_PROGRESS','AWAITING_SIGNATURE','SUBMITTED','APPROVED','INVOICED','CANCELLED')),
  CONSTRAINT chk_tbljobcard_equipment_status CHECK (equipment_status IN ('SAFE','RESTRICTED','FURTHER_WORK','OUT_OF_SERVICE','NOT_TESTED'))
);

CREATE TABLE IF NOT EXISTS atec.tbljobcardasset (
  jobcardassetid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobcardid integer NOT NULL REFERENCES atec.tbljobcard(jobcardid) ON DELETE CASCADE,
  assetid integer REFERENCES atec.tblasset(assetid) ON DELETE SET NULL,
  asset_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (jobcardid, assetid)
);

-- In lifting-industry usage, a call-out is treated as a breakdown.
UPDATE atec.tbljobcard SET job_type = 'BREAKDOWN' WHERE job_type = 'CALLOUT';
ALTER TABLE atec.tbljobcard DROP CONSTRAINT IF EXISTS chk_tbljobcard_type;
ALTER TABLE atec.tbljobcard ADD CONSTRAINT chk_tbljobcard_type
  CHECK (job_type IN ('BREAKDOWN','REPAIR','MAINTENANCE','INSTALLATION','INVESTIGATION','OTHER'));

CREATE TABLE IF NOT EXISTS atec.tbljobcardmaterial (
  materialid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobcardid integer NOT NULL REFERENCES atec.tbljobcard(jobcardid) ON DELETE CASCADE,
  quantity numeric(10,2) NOT NULL DEFAULT 1,
  description text NOT NULL,
  part_number text NOT NULL DEFAULT '',
  supplied_by text NOT NULL DEFAULT 'FB_CRANES',
  material_status text NOT NULL DEFAULT 'USED',
  CONSTRAINT chk_tbljobcardmaterial_supplier CHECK (supplied_by IN ('FB_CRANES','CUSTOMER')),
  CONSTRAINT chk_tbljobcardmaterial_status CHECK (material_status IN ('USED','RETURNED','REQUIRED'))
);

CREATE TABLE IF NOT EXISTS atec.tbljobcarddeviation (
  deviationid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobcardid integer NOT NULL REFERENCES atec.tbljobcard(jobcardid) ON DELETE CASCADE,
  assetid integer REFERENCES atec.tblasset(assetid) ON DELETE SET NULL,
  category text NOT NULL DEFAULT 'OTHER',
  severity text NOT NULL DEFAULT 'OBSERVATION',
  description text NOT NULL,
  immediate_action text NOT NULL DEFAULT '',
  further_work_required text NOT NULL DEFAULT '',
  target_date date,
  deviation_status text NOT NULL DEFAULT 'OPEN',
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tbljobcarddeviation_category CHECK (category IN ('ELECTRICAL','MECHANICAL','STRUCTURAL','CONTROLS','SAFETY','HOUSEKEEPING','OTHER')),
  CONSTRAINT chk_tbljobcarddeviation_severity CHECK (severity IN ('OBSERVATION','MINOR','MAJOR','CRITICAL')),
  CONSTRAINT chk_tbljobcarddeviation_status CHECK (deviation_status IN ('OPEN','CLOSED'))
);

CREATE TABLE IF NOT EXISTS atec.tbljobcardphoto (
  photoid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobcardid integer NOT NULL REFERENCES atec.tbljobcard(jobcardid) ON DELETE CASCADE,
  deviationid integer REFERENCES atec.tbljobcarddeviation(deviationid) ON DELETE CASCADE,
  photo_path text NOT NULL,
  photo_type text NOT NULL DEFAULT 'GENERAL',
  caption text NOT NULL DEFAULT '',
  uploaded_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tbljobcardphoto_type CHECK (photo_type IN ('GENERAL','BEFORE','AFTER','DEFECT','NAMEPLATE','TEST'))
);

CREATE INDEX IF NOT EXISTS idx_tbljobcard_client_site_status ON atec.tbljobcard(clientid, siteid, status);
CREATE INDEX IF NOT EXISTS idx_tbljobcard_assigned_status ON atec.tbljobcard(assigned_to_user_id, status);
CREATE INDEX IF NOT EXISTS idx_tbljobcardasset_jobcard ON atec.tbljobcardasset(jobcardid);
CREATE INDEX IF NOT EXISTS idx_tbljobcarddeviation_jobcard ON atec.tbljobcarddeviation(jobcardid);
CREATE INDEX IF NOT EXISTS idx_tbljobcardphoto_jobcard ON atec.tbljobcardphoto(jobcardid);

COMMIT;
