BEGIN;

ALTER TABLE atec.tbljobcard ADD COLUMN IF NOT EXISTS quote_required boolean NOT NULL DEFAULT false;
ALTER TABLE atec.tbljobcard ADD COLUMN IF NOT EXISTS return_visit_required boolean NOT NULL DEFAULT false;
ALTER TABLE atec.tbljobcard ADD COLUMN IF NOT EXISTS return_visit_reason text NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS atec.tbljobcardfollowup (
  followupid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobcardid integer NOT NULL REFERENCES atec.tbljobcard(jobcardid) ON DELETE RESTRICT,
  kind text NOT NULL CHECK (kind IN ('QUOTE','ATTENTION','REBOOK')),
  assetid integer REFERENCES atec.tblasset(assetid) ON DELETE RESTRICT,
  asset_label text NOT NULL DEFAULT '',
  description text NOT NULL,
  reported_condition text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'OPEN',
  responsible_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  due_date date,
  accelo_reference text NOT NULL DEFAULT '',
  booked_date date,
  return_jobcardid integer REFERENCES atec.tbljobcard(jobcardid) ON DELETE RESTRICT,
  notes text NOT NULL DEFAULT '',
  raised_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  CHECK ((kind='QUOTE' AND status IN ('OPEN','HANDED_OVER','CANCELLED')) OR
         (kind='ATTENTION' AND status IN ('OPEN','RESOLVED','CANCELLED')) OR
         (kind='REBOOK' AND status IN ('OPEN','WAITING','BOOKED','COMPLETED','CANCELLED'))),
  CHECK ((kind='ATTENTION' AND assetid IS NOT NULL) OR (kind<>'ATTENTION' AND assetid IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_jobcardfollowup_source ON atec.tbljobcardfollowup(jobcardid,kind,COALESCE(assetid,0));
CREATE INDEX IF NOT EXISTS idx_jobcardfollowup_open ON atec.tbljobcardfollowup(kind,status,raised_at);

-- Historic flags are reports requiring review, not a determination of current asset safety.
-- Do not guess quote or rebooking requirements from free text.
INSERT INTO atec.tbljobcardfollowup
  (jobcardid,kind,assetid,asset_label,description,reported_condition,raised_at,history)
SELECT j.jobcardid,'ATTENTION',a.assetid,
  COALESCE(NULLIF(a.assettagno,''),NULLIF(a.serialno,''),'Asset '||a.assetid),
  COALESCE(NULLIF(j.equipment_status_reason,''),'Review the equipment condition recorded on this job card'),
  j.equipment_status,COALESCE(j.submitted_at,j.created_at),
  jsonb_build_array(jsonb_build_object('at',now(),'action','Imported for review','note','Historical job-card condition; verify whether already resolved.'))
FROM atec.tbljobcard j JOIN atec.tbljobcardasset ja ON ja.jobcardid=j.jobcardid
JOIN atec.tblasset a ON a.assetid=ja.assetid
WHERE j.equipment_status IN ('OUT_OF_SERVICE','RESTRICTED') AND j.status<>'CANCELLED'
ON CONFLICT DO NOTHING;

COMMIT;
