BEGIN;

ALTER TABLE atec.tblusers DROP CONSTRAINT IF EXISTS tblusers_role_check;
ALTER TABLE atec.tblusers ADD CONSTRAINT tblusers_role_check
  CHECK (role IN ('ADMIN','MANAGER','INSPECTOR','ASSISTANT','HR','VIEWER','CUSTOMER'));

ALTER TABLE atec.tblusers
  ADD COLUMN IF NOT EXISTS manager_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS employee_number text NOT NULL DEFAULT '';

ALTER TABLE atec.tbljobcard
  ADD COLUMN IF NOT EXISTS accelo_email_sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS accelo_email_to text,
  ADD COLUMN IF NOT EXISTS accelo_email_error text;

ALTER TABLE atec.tbljobcard DROP CONSTRAINT IF EXISTS chk_tbljobcard_accelo_number;
ALTER TABLE atec.tbljobcard ADD CONSTRAINT chk_tbljobcard_accelo_number
  CHECK (customer_reference = '' OR customer_reference ~ '^[0-9]+$') NOT VALID;

ALTER TABLE atec.tblinspection DROP CONSTRAINT IF EXISTS chk_tblinspection_job_number;
ALTER TABLE atec.tblinspection ADD CONSTRAINT chk_tblinspection_job_number
  CHECK (job_number = '' OR job_number ~ '^[0-9]+$') NOT VALID;
ALTER TABLE atec.tblinspection
  ADD COLUMN IF NOT EXISTS jobcardid integer REFERENCES atec.tbljobcard(jobcardid) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS atec.tblworkschedule (
  scheduleid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_name text NOT NULL,
  employee_user_id integer NOT NULL REFERENCES atec.tblusers(userid) ON DELETE CASCADE,
  effective_from date NOT NULL,
  effective_to date,
  travel_treatment text NOT NULL DEFAULT 'SPLIT_BY_SCHEDULE',
  rounding_minutes integer NOT NULL DEFAULT 1,
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblworkschedule_dates CHECK (effective_to IS NULL OR effective_to >= effective_from),
  CONSTRAINT chk_tblworkschedule_travel CHECK (travel_treatment IN ('SPLIT_BY_SCHEDULE','ALWAYS_NORMAL','ALWAYS_OVERTIME')),
  CONSTRAINT chk_tblworkschedule_rounding CHECK (rounding_minutes IN (1,5,10,15,30))
);

CREATE TABLE IF NOT EXISTS atec.tblworkscheduleday (
  scheduledayid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheduleid integer NOT NULL REFERENCES atec.tblworkschedule(scheduleid) ON DELETE CASCADE,
  weekday integer NOT NULL,
  normal_start time,
  normal_end time,
  unpaid_break_minutes integer NOT NULL DEFAULT 0,
  is_overtime_day boolean NOT NULL DEFAULT false,
  UNIQUE (scheduleid, weekday),
  CONSTRAINT chk_tblworkscheduleday_weekday CHECK (weekday BETWEEN 0 AND 6),
  CONSTRAINT chk_tblworkscheduleday_break CHECK (unpaid_break_minutes BETWEEN 0 AND 720)
);

CREATE TABLE IF NOT EXISTS atec.tblpublicholiday (
  holiday_date date PRIMARY KEY,
  holiday_name text NOT NULL,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS atec.tbljobcardcrew (
  jobcardcrewid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobcardid integer NOT NULL REFERENCES atec.tbljobcard(jobcardid) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES atec.tblusers(userid) ON DELETE RESTRICT,
  crew_role text NOT NULL DEFAULT 'ASSISTANT',
  included_in_time boolean NOT NULL DEFAULT true,
  added_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (jobcardid, user_id),
  CONSTRAINT chk_tbljobcardcrew_role CHECK (crew_role IN ('LEAD_TECHNICIAN','ASSISTANT','ADDITIONAL_TECHNICIAN'))
);

CREATE TABLE IF NOT EXISTS atec.tbltimeentry (
  timeentryid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES atec.tblusers(userid) ON DELETE RESTRICT,
  jobcardid integer REFERENCES atec.tbljobcard(jobcardid) ON DELETE SET NULL,
  activity_date date NOT NULL,
  activity_type text NOT NULL,
  started_at timestamptz NOT NULL,
  ended_at timestamptz NOT NULL,
  customer_name_snapshot text NOT NULL DEFAULT '',
  job_number_snapshot text NOT NULL DEFAULT '',
  jobcard_reference_snapshot text NOT NULL DEFAULT '',
  brief_details text NOT NULL DEFAULT '',
  underground boolean NOT NULL DEFAULT false,
  source text NOT NULL DEFAULT 'JOB_CARD',
  source_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  employee_confirmed_at timestamptz,
  adjustment_reason text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tbltimeentry_dates CHECK (ended_at > started_at),
  CONSTRAINT chk_tbltimeentry_type CHECK (activity_type IN ('TRAVEL','WORK','STANDBY','BREAK','WORKSHOP','TRAINING','MEETING','ADMIN','WAITING','LEAVE','SICK_LEAVE','UNPAID','OTHER')),
  CONSTRAINT chk_tbltimeentry_source CHECK (source IN ('JOB_CARD','COPIED_FROM_LEAD','EMPLOYEE','MANAGER','HR'))
);

CREATE TABLE IF NOT EXISTS atec.tbldailytimesheet (
  timesheetid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES atec.tblusers(userid) ON DELETE RESTRICT,
  timesheet_date date NOT NULL,
  status text NOT NULL DEFAULT 'DRAFT',
  schedule_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  calculated_normal_hours numeric(8,2) NOT NULL DEFAULT 0,
  calculated_overtime_hours numeric(8,2) NOT NULL DEFAULT 0,
  calculated_travel_hours numeric(8,2) NOT NULL DEFAULT 0,
  calculated_standby_hours numeric(8,2) NOT NULL DEFAULT 0,
  final_normal_hours numeric(8,2) NOT NULL DEFAULT 0,
  final_overtime_hours numeric(8,2) NOT NULL DEFAULT 0,
  final_travel_hours numeric(8,2) NOT NULL DEFAULT 0,
  final_standby_hours numeric(8,2) NOT NULL DEFAULT 0,
  underground_allowance boolean NOT NULL DEFAULT false,
  adjustment_reason text NOT NULL DEFAULT '',
  employee_submitted_at timestamptz,
  manager_approved_at timestamptz,
  manager_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  hr_accepted_at timestamptz,
  hr_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  exported_at timestamptz,
  returned_reason text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, timesheet_date),
  CONSTRAINT chk_tbldailytimesheet_status CHECK (status IN ('DRAFT','AWAITING_EMPLOYEE','EMPLOYEE_SUBMITTED','MANAGER_APPROVED','HR_ACCEPTED','EXPORTED','RETURNED'))
);

CREATE TABLE IF NOT EXISTS atec.tbldailytimesheetline (
  timesheetlineid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timesheetid integer NOT NULL REFERENCES atec.tbldailytimesheet(timesheetid) ON DELETE CASCADE,
  timeentryid integer REFERENCES atec.tbltimeentry(timeentryid) ON DELETE SET NULL,
  task_number integer NOT NULL,
  activity_type text NOT NULL,
  started_at timestamptz NOT NULL,
  ended_at timestamptz NOT NULL,
  normal_hours numeric(8,2) NOT NULL DEFAULT 0,
  overtime_hours numeric(8,2) NOT NULL DEFAULT 0,
  worksheet_number text NOT NULL DEFAULT '',
  job_number text NOT NULL DEFAULT '',
  customer_name text NOT NULL DEFAULT '',
  brief_details text NOT NULL DEFAULT '',
  underground boolean NOT NULL DEFAULT false,
  UNIQUE (timesheetid, task_number)
);

CREATE TABLE IF NOT EXISTS atec.tbltimesheetaudit (
  timesheetauditid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timesheetid integer NOT NULL REFERENCES atec.tbldailytimesheet(timesheetid) ON DELETE CASCADE,
  actor_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  action text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS atec.tblaccelodelivery (
  deliveryid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobcardid integer NOT NULL REFERENCES atec.tbljobcard(jobcardid) ON DELETE CASCADE,
  recipient text NOT NULL,
  subject text NOT NULL,
  attachment_manifest jsonb NOT NULL DEFAULT '[]'::jsonb,
  delivery_status text NOT NULL DEFAULT 'PENDING',
  provider_message_id text,
  error_message text,
  requested_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  CONSTRAINT chk_tblaccelodelivery_status CHECK (delivery_status IN ('PENDING','SENT','FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_tblworkschedule_employee_dates ON atec.tblworkschedule(employee_user_id, effective_from DESC);
CREATE INDEX IF NOT EXISTS idx_tbljobcardcrew_jobcard ON atec.tbljobcardcrew(jobcardid);
CREATE INDEX IF NOT EXISTS idx_tbljobcardcrew_user ON atec.tbljobcardcrew(user_id);
CREATE INDEX IF NOT EXISTS idx_tbltimeentry_user_date ON atec.tbltimeentry(user_id, activity_date, started_at);
CREATE INDEX IF NOT EXISTS idx_tbltimeentry_jobcard ON atec.tbltimeentry(jobcardid);
CREATE INDEX IF NOT EXISTS idx_tblinspection_jobcard ON atec.tblinspection(jobcardid);
CREATE INDEX IF NOT EXISTS idx_tbldailytimesheet_status_date ON atec.tbldailytimesheet(status, timesheet_date);
CREATE INDEX IF NOT EXISTS idx_tbldailytimesheet_manager ON atec.tbldailytimesheet(manager_user_id, status);
CREATE INDEX IF NOT EXISTS idx_tbltimesheetaudit_timesheet ON atec.tbltimesheetaudit(timesheetid, created_at);
CREATE INDEX IF NOT EXISTS idx_tblaccelodelivery_jobcard ON atec.tblaccelodelivery(jobcardid, created_at DESC);

COMMIT;
