BEGIN;

CREATE TABLE IF NOT EXISTS atec.tblinspectionvisit (
  visitid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_reference text NOT NULL,
  clientid integer NOT NULL REFERENCES atec.tblclients(clientid) ON DELETE RESTRICT,
  siteid integer NOT NULL REFERENCES atec.tblsites(siteid) ON DELETE RESTRICT,
  sectionid integer REFERENCES atec.tblsection(sectionid) ON DELETE SET NULL,
  visit_type text NOT NULL DEFAULT 'COMBINED',
  planned_start_at timestamptz,
  actual_start_at timestamptz,
  actual_completion_at timestamptz,
  visit_status text NOT NULL DEFAULT 'DRAFT',
  lead_inspector_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  closed_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  notes text NOT NULL DEFAULT '',
  customer_representative text NOT NULL DEFAULT '',
  customer_reference text NOT NULL DEFAULT '',
  due_cutoff_date date,
  due_soon_days integer NOT NULL DEFAULT 0,
  include_overdue boolean NOT NULL DEFAULT true,
  include_already_due boolean NOT NULL DEFAULT true,
  include_due_during_visit boolean NOT NULL DEFAULT true,
  closure_summary jsonb,
  closure_override_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblinspectionvisit_type
    CHECK (visit_type IN ('VISUAL','LOADTEST','COMBINED','SURVEY')),
  CONSTRAINT chk_tblinspectionvisit_status
    CHECK (visit_status IN ('DRAFT','OPEN','PAUSED','RECONCILIATION_REQUIRED','COMPLETED','CANCELLED'))
);

CREATE TABLE IF NOT EXISTS atec.tblinspectionvisitasset (
  visitassetid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitid integer NOT NULL REFERENCES atec.tblinspectionvisit(visitid) ON DELETE CASCADE,
  assetid integer REFERENCES atec.tblasset(assetid) ON DELETE SET NULL,
  clientid_snapshot integer,
  siteid_snapshot integer,
  sectionid_snapshot integer,
  equipmenttypeid_snapshot integer,
  equipmenttype_snapshot text,
  assettag_snapshot text,
  serial_snapshot text,
  description_snapshot text,
  due_reason text NOT NULL DEFAULT '',
  visual_due_date_at_start date,
  loadtest_due_date_at_start date,
  visual_due_flag boolean NOT NULL DEFAULT false,
  loadtest_due_flag boolean NOT NULL DEFAULT false,
  overdue_flag boolean NOT NULL DEFAULT false,
  required_inspection_scope text NOT NULL DEFAULT 'VISUAL',
  reconciliation_status text NOT NULL DEFAULT 'OUTSTANDING',
  disposition_reason text,
  disposition_comments text,
  customer_confirmation text,
  deferred_follow_up_date date,
  linked_visual_testid integer REFERENCES atec.tblinspection(testid) ON DELETE SET NULL,
  linked_loadtest_testid integer REFERENCES atec.tblinspection(testid) ON DELETE SET NULL,
  first_scanned_at timestamptz,
  completed_at timestamptz,
  resolved_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  resolution_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tblinspectionvisitasset_scope
    CHECK (required_inspection_scope IN ('VISUAL','LOADTEST','BOTH','SURVEY')),
  CONSTRAINT chk_tblinspectionvisitasset_status
    CHECK (reconciliation_status IN (
      'OUTSTANDING',
      'COMPLETED',
      'NOT_FOUND',
      'OUT_OF_SERVICE',
      'REMOVED_FROM_SITE',
      'INACCESSIBLE',
      'DEFERRED',
      'CUSTOMER_CONFIRMED_REMOVED',
      'DUPLICATE_RECORD',
      'NOT_REQUIRED',
      'OTHER'
    ))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tblinspectionvisitasset_visit_asset_scope
  ON atec.tblinspectionvisitasset(visitid, assetid, required_inspection_scope)
  WHERE assetid IS NOT NULL;

CREATE TABLE IF NOT EXISTS atec.tblinspectionvisitmember (
  visitmemberid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitid integer NOT NULL REFERENCES atec.tblinspectionvisit(visitid) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES atec.tblusers(userid) ON DELETE RESTRICT,
  role_label text NOT NULL DEFAULT 'INSPECTOR',
  assigned_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  removed_at timestamptz,
  UNIQUE (visitid, user_id)
);

CREATE TABLE IF NOT EXISTS atec.tblinspectionvisitactivity (
  visitactivityid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitid integer REFERENCES atec.tblinspectionvisit(visitid) ON DELETE CASCADE,
  visitassetid integer REFERENCES atec.tblinspectionvisitasset(visitassetid) ON DELETE SET NULL,
  user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  activity_type text NOT NULL,
  details jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS atec.tblinspectionvisitdiscovery (
  discoveryid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitid integer NOT NULL REFERENCES atec.tblinspectionvisit(visitid) ON DELETE CASCADE,
  description text NOT NULL DEFAULT '',
  equiptypeid integer REFERENCES atec.tblequiptype(equiptypeid) ON DELETE SET NULL,
  serialno text,
  assettagno text,
  section_location text,
  photo_path text,
  notes text,
  customer_comment text,
  inspection_performed boolean NOT NULL DEFAULT false,
  duplicate_warning jsonb,
  linked_assetid integer REFERENCES atec.tblasset(assetid) ON DELETE SET NULL,
  created_by_user_id integer REFERENCES atec.tblusers(userid) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tblinspectionvisit_client_site_status
  ON atec.tblinspectionvisit(clientid, siteid, visit_status);

CREATE INDEX IF NOT EXISTS idx_tblinspectionvisit_status_start
  ON atec.tblinspectionvisit(visit_status, planned_start_at DESC);

CREATE INDEX IF NOT EXISTS idx_tblinspectionvisitasset_visit_status
  ON atec.tblinspectionvisitasset(visitid, reconciliation_status);

CREATE INDEX IF NOT EXISTS idx_tblinspectionvisitasset_asset
  ON atec.tblinspectionvisitasset(assetid);

CREATE INDEX IF NOT EXISTS idx_tblinspectionvisitasset_outstanding
  ON atec.tblinspectionvisitasset(visitid, overdue_flag, required_inspection_scope)
  WHERE reconciliation_status = 'OUTSTANDING';

CREATE INDEX IF NOT EXISTS idx_tblinspectionvisitactivity_visit_created
  ON atec.tblinspectionvisitactivity(visitid, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tblinspectionvisitdiscovery_visit
  ON atec.tblinspectionvisitdiscovery(visitid, created_at DESC);

-- Read-only audit:
-- SELECT visit_status, count(*) FROM atec.tblinspectionvisit GROUP BY visit_status;
-- SELECT visitid, count(*) AS due_assets FROM atec.tblinspectionvisitasset GROUP BY visitid ORDER BY visitid DESC LIMIT 20;
-- SELECT visitid, reconciliation_status, count(*) FROM atec.tblinspectionvisitasset GROUP BY visitid, reconciliation_status ORDER BY visitid DESC;
-- SELECT visitid, count(*) AS discoveries FROM atec.tblinspectionvisitdiscovery GROUP BY visitid ORDER BY visitid DESC LIMIT 20;

-- Rollback guidance:
-- DROP TABLE IF EXISTS atec.tblinspectionvisitdiscovery;
-- DROP TABLE IF EXISTS atec.tblinspectionvisitactivity;
-- DROP TABLE IF EXISTS atec.tblinspectionvisitmember;
-- DROP TABLE IF EXISTS atec.tblinspectionvisitasset;
-- DROP TABLE IF EXISTS atec.tblinspectionvisit;

COMMIT;
